# Generated by Copilot
from flask import Blueprint, request, jsonify
from services import auth_service

bp = Blueprint('auth', __name__, url_prefix='/api/auth')


@bp.post('/crear-key')
def crear_key():
    token_portal = request.form.get('token_portal', '').strip()
    if not token_portal:
        return jsonify({'success': False, 'error': 'El campo token_portal es requerido'}), 400

    resultado = auth_service.crear_key(token_portal)
    return jsonify(resultado)


@bp.post('/generar-token')
def generar_token():
    api_key = request.form.get('api_key', '').strip()
    if not api_key:
        return jsonify({'success': False, 'error': 'El campo api_key es requerido'}), 400

    resultado = auth_service.generar_token(api_key)
    return jsonify(resultado)
