# Generated by Copilot
import base64
from flask import Blueprint, request, jsonify
from services import csf_service

bp = Blueprint('csf', __name__, url_prefix='/api/csf')


@bp.post('/descargar')
def descargar():
    """Descarga la Constancia de Situación Fiscal y devuelve el PDF en base64."""
    rfc           = request.form.get('rfc', '').strip()
    authorization = request.form.get('authorization', '').strip()
    contrasena    = request.form.get('contrasena', '').strip()
    llave_privada = request.files.get('llavePrivada')
    certificado   = request.files.get('certificado')

    if not all([rfc, authorization, contrasena, llave_privada, certificado]):
        return jsonify({'success': False, 'error': 'Todos los campos FIEL son requeridos'}), 400

    resultado = csf_service.descargar_csf(rfc, authorization, contrasena, llave_privada, certificado)

    if resultado['success']:
        return jsonify({
            'success':      True,
            'pdf_base64':   base64.b64encode(resultado['pdf_bytes']).decode(),
            'file_name':    resultado['file_name'],
            'content_type': resultado['content_type'],
        })

    return jsonify({'success': False, 'error': resultado['error']}), 400
