# Generated by Copilot
import base64
from flask import Blueprint, request, jsonify
from services import csf_service

bp = Blueprint('csf', __name__, url_prefix='/api/csf')


@bp.post('/descargar')
def descargar():
    """Descarga la Constancia de Situación Fiscal. Soporta FIEL y CIEC."""
    rfc           = request.form.get('rfc', '').strip()
    authorization = request.form.get('authorization', '').strip()
    metodo        = request.form.get('metodo', 'fiel').strip().lower()

    if not all([rfc, authorization]):
        return jsonify({'success': False, 'error': 'RFC y Token son requeridos'}), 400

    if metodo == 'ciec':
        ciec = request.form.get('ciec', '').strip()
        if not ciec:
            return jsonify({'success': False, 'error': 'La Clave CIEC es requerida'}), 400
        resultado = csf_service.descargar_csf_ciec(rfc, authorization, ciec)
    else:
        contrasena    = request.form.get('contrasena', '').strip()
        llave_privada = request.files.get('llavePrivada')
        certificado   = request.files.get('certificado')

        if not all([contrasena, llave_privada, certificado]):
            return jsonify({'success': False, 'error': 'Contraseña, llave privada y certificado son requeridos para FIEL'}), 400

        resultado = csf_service.descargar_csf(rfc, authorization, contrasena, llave_privada, certificado)

    if resultado['success']:
        return jsonify({
            'success':      True,
            'pdf_base64':   base64.b64encode(resultado['pdf_bytes']).decode(),
            'file_name':    resultado['file_name'],
            'content_type': resultado['content_type'],
        })

    return jsonify({'success': False, 'error': resultado['error']}), 400
