# Generated by Copilot
from flask import Blueprint, request, jsonify
from services import factura_service
from datetime import datetime, timedelta

bp = Blueprint('facturas', __name__, url_prefix='/api/facturas')


@bp.post('/consultar')
def consultar():
    """Consulta facturas. Soporta FIEL (POST multipart) y CIEC (GET con Secret header)."""
    rfc           = request.form.get('rfc', '').strip()
    authorization = request.form.get('authorization', '').strip()
    metodo        = request.form.get('metodo', 'fiel').strip().lower()

    if not all([rfc, authorization]):
        return jsonify({'success': False, 'error': 'RFC y Token son requeridos'}), 400

    today  = datetime.now()
    ago_30 = today - timedelta(days=30)
    fmt    = '%Y-%m-%d %H:%M:%S'

    if metodo == 'ciec':
        ciec = request.form.get('ciec', '').strip()
        if not ciec:
            return jsonify({'success': False, 'error': 'La Clave CIEC es requerida'}), 400

        resultado = factura_service.consultar_facturas_ciec(
            rfc=rfc,
            authorization=authorization,
            ciec=ciec,
            fecha_inicial=request.form.get('fecha_inicial', ago_30.strftime(fmt)),
            tipo=request.form.get('tipo', 'recibidos'),
            estatus_factura=int(request.form.get('estatus_factura', -1)),
            tipo_busqueda=int(request.form.get('tipo_busqueda', 1)),
        )
    else:
        contrasena    = request.form.get('contrasena', '').strip()
        llave_privada = request.files.get('llavePrivada')
        certificado   = request.files.get('certificado')

        if not all([contrasena, llave_privada, certificado]):
            return jsonify({'success': False, 'error': 'Contraseña, llave privada y certificado son requeridos para FIEL'}), 400

        resultado = factura_service.consultar_facturas(
            rfc=rfc,
            authorization=authorization,
            contrasena=contrasena,
            llave_privada=llave_privada,
            certificado=certificado,
            tipo_busqueda=int(request.form.get('tipo_busqueda', 1)),
            estatus_factura=int(request.form.get('estatus_factura', -1)),
            fecha_inicial=request.form.get('fecha_inicial', ago_30.strftime(fmt)),
            fecha_final=request.form.get('fecha_final', today.strftime(fmt)),
            tipo=request.form.get('tipo', 'recibidos'),
            descarga_comprobantes=request.form.get('descarga_comprobantes', 'false').lower() == 'true',
            request_id=request.form.get('request_id', ''),
        )

    if resultado['success']:
        return jsonify({
            'success':    True,
            'data':       resultado['data'],
            'request_id': resultado.get('request_id'),
            'message':    resultado.get('message', 'Consulta exitosa'),
        })

    return jsonify({'success': False, 'error': resultado['error']}), 400
