<?php
// Generated by Copilot

/**
 * Configuración de la API para consulta de facturas SAT
 */
class ApiConfig
{
    public const BASE_URL = 'https://api.sat-go.com//api/v2';
    
    public const ENDPOINTS = [
        'CONSULTAR_FACFIEL' => '/Consultar/facfiel',
        'CONSULTAR_CSFFIEL' => '/Consultar/csffiel',
        'CONSULTAR_OCFIEL'  => '/Consultar/ocfiel',
        'CONSULTAR_DECFIEL' => '/Consultar/decfiel'
    ];
    
    public const TIMEOUT = 120; // Generated by Copilot - 2 minutos
    
    public const DEFAULT_HEADERS = [
        'Accept' => '*/*',
        'User-Agent' => 'PHP-SAT-Client/1.0',
        'Cache-Control' => 'no-cache'
    ];
}

/**
 * Valores por defecto del formulario
 */
class FormDefaults
{
    public const RFC = 'XAXX010101000';
    public const CONTRASENA = '';
    public const TIPO_BUSQUEDA = 1;
    public const ESTATUS_FACTURA = -1;
    public const TIPO = 'recibidos';
    public const DESCARGA_COMPROBANTES = false;
    public const FECHA_INICIAL = '2025-12-01T00:00:00';
    public const FECHA_FINAL = '2025-12-02T23:59:59';
}
