import { useState } from 'react'
import { Container, Navbar, Nav, Card } from 'react-bootstrap' // Generated by Copilot
import ConsultaFacturaForm from './components/ConsultaFacturaForm'
import FacturaResultados from './components/FacturaResultados'
import OpinionCumplimientoForm from './components/OpinionCumplimientoForm'
import CsfForm from './components/CsfForm'
import FielDataForm from './components/FielDataForm'
import type { FielData, FielFiles } from './types/FielTypes'
import { FORM_DEFAULTS } from './config/api'
import './App.css'

// Generated by Copilot - Tipos de vista
type ViewType = 'facturas' | 'opinion-cumplimiento' | 'csf';

function App() {
  const [resultados, setResultados] = useState<any>(null)
  const [activeView, setActiveView] = useState<ViewType>('facturas')
  
  // Generated by Copilot - Datos FIEL compartidos
  const [fielData, setFielData] = useState<FielData>({
    rfc: FORM_DEFAULTS.RFC,
    authorization: '',
    contrasena: FORM_DEFAULTS.CONTRASENA
  });
  const [files, setFiles] = useState<FielFiles>({});

  const handleConsultaResult = (data: any) => {
    setResultados(data);
  };

  const handleNavClick = (view: ViewType) => {
    setActiveView(view);
    setResultados(null); // Limpiar resultados al cambiar de vista
  };

  const handleFielChange = (field: keyof FielData, value: string) => {
    setFielData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleFileChange = (field: keyof FielFiles, file: File | null) => {
    if (file) {
      setFiles(prev => ({
        ...prev,
        [field]: file
      }));
    }
  };

  return (
    <>
      {/* Generated by Copilot - Bootstrap Navbar */}
      <Navbar bg="dark" variant="dark" expand="lg" className="mb-4">
        <Container>
          <Navbar.Brand href="#home">SAT Go Cliente</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="me-auto">
              <Nav.Link 
                href="#consultar" 
                active={activeView === 'facturas'}
                onClick={() => handleNavClick('facturas')}
              >
                Consultar Facturas
              </Nav.Link>
              <Nav.Link 
                href="#opinion-cumplimiento"
                active={activeView === 'opinion-cumplimiento'}
                onClick={() => handleNavClick('opinion-cumplimiento')}
              >
                Opinión de Cumplimiento
              </Nav.Link>
              <Nav.Link 
                href="#csf"
                active={activeView === 'csf'}
                onClick={() => handleNavClick('csf')}
              >
                CSF
              </Nav.Link>
              <Nav.Link href="#about">Acerca de</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>

      <Container>
        {/* Generated by Copilot - Datos FIEL compartidos */}
        <Card className="mb-4">
          <Card.Header>
            <Card.Title className="mb-0">Información FIEL</Card.Title>
          </Card.Header>
          <Card.Body>
            <FielDataForm
              fielData={fielData}
              files={files}
              onFielDataChange={handleFielChange}
              onFileChange={handleFileChange}
              filesRequired={false}
              showToken={true}
            />
          </Card.Body>
        </Card>

        {/* Generated by Copilot - Renderizado condicional basado en vista activa */}
        {activeView === 'facturas' && (
          <>
            <ConsultaFacturaForm onResult={handleConsultaResult} fielData={fielData} files={files} />
            {resultados && <FacturaResultados data={resultados} />}
          </>
        )}
        
        {activeView === 'opinion-cumplimiento' && (
          <OpinionCumplimientoForm onResult={handleConsultaResult} fielData={fielData} files={files} />
        )}
        
        {activeView === 'csf' && (
          <CsfForm onResult={handleConsultaResult} fielData={fielData} files={files} />
        )}
      </Container>
    </>
  )
}

export default App
