import { useState } from 'react'
import { Container, Navbar, Nav } from 'react-bootstrap' // Generated by Copilot
import ConsultaFacturaForm from './components/ConsultaFacturaForm'
import FacturaResultados from './components/FacturaResultados'
import './App.css'

function App() {
  const [resultados, setResultados] = useState<any>(null)

  const handleConsultaResult = (data: any) => {
    setResultados(data);
  };

  return (
    <>
      {/* Generated by Copilot - Bootstrap Navbar */}
      <Navbar bg="dark" variant="dark" expand="lg" className="mb-4">
        <Container>
          <Navbar.Brand href="#home">SAT Go Cliente</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="me-auto">
              <Nav.Link href="#consultar">Consultar Facturas</Nav.Link>
              <Nav.Link href="#about">Acerca de</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>

      <Container>
        {/* Generated by Copilot - Formulario de consulta */}
        <ConsultaFacturaForm onResult={handleConsultaResult} />
        
        {/* Generated by Copilot - Resultados de la consulta */}
        {resultados && <FacturaResultados data={resultados} />}
      </Container>
    </>
  )
}

export default App
