// Generated by Copilot
using Microsoft.AspNetCore.Mvc;
using SatGoCliente.Services;

namespace SatGoCliente.Controllers
{
    /// <summary>
    /// Controlador de autenticación SAT-GO:
    ///  1. Genera API Key permanente a partir del token del portal
    ///  2. Genera JWT de corta duración a partir de la API Key
    /// </summary>
    public class AuthController : Controller
    {
        private readonly IAuthService _auth_service;

        public AuthController(IAuthService auth_service)
        {
            _auth_service = auth_service;
        }

        /// <summary>
        /// Crea la API Key permanente usando el token obtenido del portal web.sat-go.com
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> CrearKey([FromBody] CrearKeyRequest request)
        {
            if (string.IsNullOrWhiteSpace(request?.TokenPortal))
                return Json(new { success = false, error = "El token del portal es requerido" });

            var resultado = await _auth_service.CreateKeyAsync(request.TokenPortal.Trim());

            return Json(new
            {
                success = resultado.Success,
                key = resultado.Key,
                message = resultado.Message,
                error = resultado.Error
            });
        }

        /// <summary>
        /// Genera un JWT de corta duración usando la API Key permanente.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> GenerarToken([FromBody] GenerarTokenRequest request)
        {
            if (string.IsNullOrWhiteSpace(request?.ApiKey))
                return Json(new { success = false, error = "La API Key es requerida" });

            var resultado = await _auth_service.GenerarTokenAsync(request.ApiKey.Trim());

            return Json(new
            {
                success = resultado.Success,
                accessToken = resultado.AccessToken,
                message = resultado.Message,
                error = resultado.Error
            });
        }
    }

    public class CrearKeyRequest
    {
        public string? TokenPortal { get; set; }
    }

    public class GenerarTokenRequest
    {
        public string? ApiKey { get; set; }
    }
}
