// Generated by Copilot
using Microsoft.AspNetCore.Mvc;
using SatGoCliente.Models;
using SatGoCliente.Services;

namespace SatGoCliente.Controllers
{
    /// <summary>
    /// Controlador unificado para consultas SAT
    /// </summary>
    public class ConsultaSatController : Controller
    {
        private readonly IFacturaService _factura_service;
        private readonly IOpinionCumplimientoService _opinion_service;
        private readonly ICsfService _csf_service;
        private readonly ILogger<ConsultaSatController> _logger;

        public ConsultaSatController(
            IFacturaService factura_service,
            IOpinionCumplimientoService opinion_service,
            ICsfService csf_service,
            ILogger<ConsultaSatController> logger)
        {
            _factura_service = factura_service;
            _opinion_service = opinion_service;
            _csf_service = csf_service;
            _logger = logger;
        }

        /// <summary>
        /// Muestra la vista principal con pestañas
        /// </summary>
        [HttpGet]
        public IActionResult Index(string tab = "facturas")
        {
            var model = new ConsultaSatViewModel
            {
                ActiveTab = tab,
                FechaInicial = DateTime.Today.AddDays(-30),
                FechaFinal = DateTime.Today
            };
            return View(model);
        }

        /// <summary>
        /// Consulta facturas via AJAX
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> ConsultarFacturasAjax(ConsultaSatViewModel model)
        {
            // Validar campos FIEL
            if (string.IsNullOrEmpty(model.Rfc) || 
                string.IsNullOrEmpty(model.Authorization) || 
                string.IsNullOrEmpty(model.Contrasena))
            {
                return Json(new { success = false, error = "Por favor complete todos los campos FIEL requeridos" });
            }

            if (model.LlavePrivada == null || model.Certificado == null)
            {
                return Json(new { success = false, error = "Los archivos de llave privada y certificado son requeridos" });
            }

            // Crear modelo de factura
            var factura_model = new ConsultaFacturaViewModel
            {
                Rfc = model.Rfc,
                Authorization = model.Authorization,
                Contrasena = model.Contrasena,
                LlavePrivada = model.LlavePrivada,
                Certificado = model.Certificado,
                RequestId = model.RequestId,
                FechaInicial = model.FechaInicial?.ToString("yyyy-MM-ddTHH:mm:ss") ?? DateTime.Now.AddDays(-30).ToString("yyyy-MM-ddTHH:mm:ss"),
                FechaFinal = model.FechaFinal?.ToString("yyyy-MM-ddTHH:mm:ss") ?? DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss"),
                TipoBusqueda = model.TipoSolicitud == "Metadata" ? 2 : 1,
                Tipo = string.IsNullOrEmpty(model.RfcEmisor) ? "recibidos" : "emitidos"
            };

            var resultado = await _factura_service.ConsultarFacturasAsync(factura_model);

            return Json(new { 
                success = resultado.Success, 
                message = resultado.Message,
                error = resultado.Error,
                requestId = resultado.RequestId,
                data = resultado.Data
            });
        }

        /// <summary>
        /// Descarga Opinión de Cumplimiento via AJAX
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> DescargarOpinionAjax(ConsultaSatViewModel model)
        {
            // Validar campos FIEL
            if (string.IsNullOrEmpty(model.Rfc) || 
                string.IsNullOrEmpty(model.Authorization) || 
                string.IsNullOrEmpty(model.Contrasena))
            {
                return Json(new { success = false, error = "Por favor complete todos los campos FIEL requeridos" });
            }

            if (model.LlavePrivada == null || model.Certificado == null)
            {
                return Json(new { success = false, error = "Los archivos de llave privada y certificado son requeridos" });
            }

            // Crear modelo de opinión
            var opinion_model = new OpinionCumplimientoViewModel
            {
                Rfc = model.Rfc,
                Authorization = model.Authorization,
                Contrasena = model.Contrasena,
                LlavePrivada = model.LlavePrivada,
                Certificado = model.Certificado
            };

            var resultado = await _opinion_service.DescargarOpinionAsync(opinion_model);

            if (resultado.Success && resultado.PdfData != null)
            {
                // Devolver PDF como base64 para descarga en cliente
                var base64 = Convert.ToBase64String(resultado.PdfData);
                return Json(new { 
                    success = true, 
                    pdfBase64 = base64,
                    fileName = resultado.FileName ?? "OpinionDeCumplimiento.pdf",
                    contentType = resultado.ContentType ?? "application/pdf"
                });
            }
            else
            {
                return Json(new { 
                    success = false, 
                    error = resultado.Error ?? resultado.Message ?? "Error desconocido" 
                });
            }
        }

        /// <summary>
        /// Descarga CSF via AJAX
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> DescargarCsfAjax(ConsultaSatViewModel model)
        {
            // Validar campos FIEL
            if (string.IsNullOrEmpty(model.Rfc) || 
                string.IsNullOrEmpty(model.Authorization) || 
                string.IsNullOrEmpty(model.Contrasena))
            {
                return Json(new { success = false, error = "Por favor complete todos los campos FIEL requeridos" });
            }

            if (model.LlavePrivada == null || model.Certificado == null)
            {
                return Json(new { success = false, error = "Los archivos de llave privada y certificado son requeridos" });
            }

            // Crear modelo
            var csf_model = new OpinionCumplimientoViewModel
            {
                Rfc = model.Rfc,
                Authorization = model.Authorization,
                Contrasena = model.Contrasena,
                LlavePrivada = model.LlavePrivada,
                Certificado = model.Certificado
            };

            var resultado = await _csf_service.DescargarCsfAsync(csf_model);

            if (resultado.Success && resultado.PdfData != null)
            {
                // Devolver PDF como base64 para descarga en cliente
                var base64 = Convert.ToBase64String(resultado.PdfData);
                return Json(new { 
                    success = true, 
                    pdfBase64 = base64,
                    fileName = resultado.FileName ?? "ConstanciaSituacionFiscal.pdf",
                    contentType = resultado.ContentType ?? "application/pdf"
                });
            }
            else
            {
                return Json(new { 
                    success = false, 
                    error = resultado.Error ?? resultado.Message ?? "Error desconocido" 
                });
            }
        }

        /// <summary>
        /// Descarga la Opinión de Cumplimiento
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DescargarOpinion(ConsultaSatViewModel model)
        {
            model.ActiveTab = "opinion";

            // Validar campos FIEL
            if (string.IsNullOrEmpty(model.Rfc) || 
                string.IsNullOrEmpty(model.Authorization) || 
                string.IsNullOrEmpty(model.Contrasena))
            {
                model.Error = "Por favor complete todos los campos FIEL requeridos";
                return View("Index", model);
            }

            if (model.LlavePrivada == null || model.Certificado == null)
            {
                model.Error = "Los archivos de llave privada y certificado son requeridos";
                return View("Index", model);
            }

            // Crear modelo de opinión
            var opinion_model = new OpinionCumplimientoViewModel
            {
                Rfc = model.Rfc,
                Authorization = model.Authorization,
                Contrasena = model.Contrasena,
                LlavePrivada = model.LlavePrivada,
                Certificado = model.Certificado
            };

            var resultado = await _opinion_service.DescargarOpinionAsync(opinion_model);

            if (resultado.Success && resultado.PdfData != null)
            {
                return File(
                    resultado.PdfData,
                    resultado.ContentType ?? "application/pdf",
                    resultado.FileName ?? "OpinionDeCumplimiento.pdf"
                );
            }
            else
            {
                model.Error = resultado.Error ?? resultado.Message ?? "Error desconocido";
                return View("Index", model);
            }
        }
    }
}
