// Generated by Copilot
using Microsoft.AspNetCore.Mvc;
using SatGoCliente.Models;
using SatGoCliente.Services;

namespace SatGoCliente.Controllers
{
    /// <summary>
    /// Controlador para la consulta de facturas
    /// </summary>
    public class FacturasController : Controller
    {
        private readonly IFacturaService _factura_service;
        private readonly ILogger<FacturasController> _logger;

        public FacturasController(IFacturaService factura_service, ILogger<FacturasController> logger)
        {
            _factura_service = factura_service;
            _logger = logger;
        }

        /// <summary>
        /// Muestra el formulario de consulta de facturas
        /// </summary>
        [HttpGet]
        public IActionResult Index()
        {
            var model = new ConsultaFacturaViewModel
            {
                FechaInicial = DateTime.Now.AddDays(-30).ToString("yyyy-MM-ddTHH:mm:ss"),
                FechaFinal = DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss")
            };
            
            return View(model);
        }

        /// <summary>
        /// Procesa la consulta de facturas
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(ConsultaFacturaViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var resultado = await _factura_service.ConsultarFacturasAsync(model);

                if (resultado.Success)
                {
                    model.Success = true;
                    model.Resultado = resultado.Data;
                    
                    // Guardar el RequestId para reutilizar la sesión
                    if (!string.IsNullOrEmpty(resultado.RequestId))
                    {
                        model.RequestId = resultado.RequestId;
                    }

                    TempData["SuccessMessage"] = resultado.Message;
                }
                else
                {
                    model.Success = false;
                    model.Error = resultado.Error;
                    TempData["ErrorMessage"] = resultado.Message;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al procesar consulta de facturas");
                model.Error = ex.Message;
                TempData["ErrorMessage"] = "Error inesperado al realizar la consulta";
            }

            return View(model);
        }
    }
}
