// Generated by Copilot
using Microsoft.AspNetCore.Mvc;
using SatGoCliente.Models;
using SatGoCliente.Services;

namespace SatGoCliente.Controllers
{
    /// <summary>
    /// Controlador para Opinión de Cumplimiento
    /// </summary>
    public class OpinionCumplimientoController : Controller
    {
        private readonly IOpinionCumplimientoService _opinion_service;
        private readonly ILogger<OpinionCumplimientoController> _logger;

        public OpinionCumplimientoController(
            IOpinionCumplimientoService opinion_service,
            ILogger<OpinionCumplimientoController> logger)
        {
            _opinion_service = opinion_service;
            _logger = logger;
        }

        /// <summary>
        /// Muestra el formulario de descarga de Opinión de Cumplimiento
        /// </summary>
        [HttpGet]
        public IActionResult Index()
        {
            return View(new OpinionCumplimientoViewModel());
        }

        /// <summary>
        /// Procesa la descarga de la Opinión de Cumplimiento
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Descargar(OpinionCumplimientoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Error = "Por favor complete todos los campos requeridos";
                return View("Index", model);
            }

            var resultado = await _opinion_service.DescargarOpinionAsync(model);

            if (resultado.Success && resultado.PdfData != null)
            {
                return File(
                    resultado.PdfData,
                    resultado.ContentType ?? "application/pdf",
                    resultado.FileName ?? "OpinionDeCumplimiento.pdf"
                );
            }
            else
            {
                model.Error = resultado.Error ?? resultado.Message ?? "Error desconocido";
                return View("Index", model);
            }
        }
    }
}
