# Generated by Copilot
import logging
import urllib3
from flask import Flask, render_template
from routes import facturas, oc, csf

# Deshabilitar advertencias de SSL en modo desarrollo
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
)

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16 MB máximo por archivo

# Registrar blueprints
app.register_blueprint(facturas.bp)
app.register_blueprint(oc.bp)
app.register_blueprint(csf.bp)


@app.get('/')
def index():
    return render_template('index.html')


if __name__ == '__main__':
    app.run(debug=True, port=8000)
