// Generated by Copilot
using System.Text.Json;

namespace SatGoCliente.Services
{
    /// <summary>
    /// Servicio de autenticación para SAT-GO.
    ///
    /// Flujo:
    ///  1. CreateKeyAsync(tokenPortal)  → POST /api/v1/Users/CreateKey → API Key permanente
    ///  2. GenerarTokenAsync(apiKey)    → POST /api/Auth/token?key=... → JWT de corta duración
    /// </summary>
    public class AuthService : IAuthService
    {
        private readonly HttpClient _http_client;
        private readonly ILogger<AuthService> _logger;
        private const string BASE_URL_V1 = "https://api.sat-go.com";

        public AuthService(HttpClient http_client, ILogger<AuthService> logger)
        {
            _http_client = http_client;
            _logger = logger;
        }

        /// <summary>
        /// Crea o recupera la API Key permanente usando el token del portal web.
        /// </summary>
        public async Task<CreateKeyResponse> CreateKeyAsync(string tokenPortal)
        {
            try
            {
                var url = $"{BASE_URL_V1}/api/v1/Users/CreateKey";

                using var request = new HttpRequestMessage(HttpMethod.Post, url);
                request.Headers.Add("Authorization", $"Bearer {tokenPortal}");
                request.Headers.Add("Accept", "application/json, text/plain, */*");
                request.Headers.Add("Cache-Control", "no-cache");
                // Body vacío intencionalmente — la API solo requiere el header Authorization
                request.Content = new StringContent(string.Empty);
                request.Content.Headers.ContentType = null;

                var response = await _http_client.SendAsync(request);
                var raw = await response.Content.ReadAsStringAsync();

                if (response.IsSuccessStatusCode)
                {
                    var key = ExtractStringValue(raw, new[] { "key", "Key", "apiKey", "ApiKey", "data", "result", "value" });
                    return new CreateKeyResponse
                    {
                        Success = true,
                        Key = key ?? raw,
                        Message = "API Key obtenida correctamente",
                        RawResponse = raw
                    };
                }

                var error_message = ExtractErrorMessage(raw, (int)response.StatusCode);
                _logger.LogError("Error al crear API Key: {StatusCode} - {Content}", response.StatusCode, raw);

                return new CreateKeyResponse
                {
                    Success = false,
                    Error = error_message,
                    Message = "Error al crear la API Key",
                    RawResponse = raw
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error inesperado al crear API Key");
                return new CreateKeyResponse
                {
                    Success = false,
                    Error = ex.Message,
                    Message = "Error inesperado al crear la API Key"
                };
            }
        }

        /// <summary>
        /// Genera un JWT de corta duración a partir de la API Key permanente.
        /// </summary>
        public async Task<GenerarTokenResponse> GenerarTokenAsync(string apiKey)
        {
            try
            {
                var url = $"{BASE_URL_V1}/api/Auth/token?key={Uri.EscapeDataString(apiKey)}";

                using var request = new HttpRequestMessage(HttpMethod.Post, url);
                request.Headers.Add("Accept", "application/json, text/plain, */*");
                request.Headers.Add("Cache-Control", "no-cache");
                request.Content = new StringContent(string.Empty);
                request.Content.Headers.ContentType = null;

                var response = await _http_client.SendAsync(request);
                var raw = await response.Content.ReadAsStringAsync();

                if (response.IsSuccessStatusCode)
                {
                    var token = ExtractStringValue(raw, new[] { "access_token", "accessToken", "token", "Token", "jwt", "value", "data", "result" });
                    return new GenerarTokenResponse
                    {
                        Success = true,
                        AccessToken = token ?? raw,
                        Message = "Token generado correctamente",
                        RawResponse = raw
                    };
                }

                var error_message = ExtractErrorMessage(raw, (int)response.StatusCode);
                _logger.LogError("Error al generar token: {StatusCode} - {Content}", response.StatusCode, raw);

                return new GenerarTokenResponse
                {
                    Success = false,
                    Error = error_message,
                    Message = "Error al generar el token",
                    RawResponse = raw
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error inesperado al generar token");
                return new GenerarTokenResponse
                {
                    Success = false,
                    Error = ex.Message,
                    Message = "Error inesperado al generar el token"
                };
            }
        }

        // -------------------------------------------------------------------------

        /// <summary>
        /// Intenta extraer un valor string de la respuesta cruda de la API.
        /// Soporta: texto plano, JSON string, JSON objeto (plano o anidado como tokens.access.value).
        /// </summary>
        private static string? ExtractStringValue(string raw, string[] fields)
        {
            raw = raw.Trim();

            try
            {
                using var doc = JsonDocument.Parse(raw);
                var root = doc.RootElement;

                if (root.ValueKind == JsonValueKind.String)
                    return root.GetString();

                if (root.ValueKind == JsonValueKind.Object)
                {
                    // Estructura SAT-GO: tokens.access.value
                    if (root.TryGetProperty("tokens", out var tokens) &&
                        tokens.TryGetProperty("access", out var access) &&
                        access.TryGetProperty("value", out var val) &&
                        val.ValueKind == JsonValueKind.String)
                    {
                        return val.GetString();
                    }

                    // Campos planos conocidos
                    foreach (var field in fields)
                    {
                        if (root.TryGetProperty(field, out var prop) && prop.ValueKind == JsonValueKind.String)
                            return prop.GetString();
                    }
                }

                return null;
            }
            catch (JsonException)
            {
                // No es JSON válido → texto plano
                return string.IsNullOrWhiteSpace(raw) ? null : raw;
            }
        }

        private static string ExtractErrorMessage(string raw, int http_code)
        {
            try
            {
                using var doc = JsonDocument.Parse(raw);
                var root = doc.RootElement;

                foreach (var field in new[] { "message", "title", "detail" })
                {
                    if (root.TryGetProperty(field, out var prop) && prop.ValueKind == JsonValueKind.String)
                        return prop.GetString() ?? $"Error HTTP {http_code}";
                }
            }
            catch (JsonException) { }

            return $"Error HTTP {http_code}";
        }
    }
}
