// Generated by Copilot
using System.Net.Http.Headers;
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    /// <summary>
    /// Servicio de Declaraciones SAT.
    ///
    /// FIEL: POST /api/v2/Consultar/decfiel
    ///       Query: ejercicio, mes, tipoDocumento (declaracion|pago), requestId
    ///       Body:  multipart — Contrasena, llavePrivada, Certificado
    ///       Headers: RFC, Authorization: Bearer
    ///
    /// CIEC: GET  /api/v2/Consultar/dec
    ///       Query: ejercicio, mes, requestId
    ///       Headers: RFC, Authorization: Bearer, Secret: {ciec}
    ///
    /// Respuesta: archivo ZIP binario.
    /// </summary>
    public class DeclaracionService : IDeclaracionService
    {
        private readonly HttpClient _http_client;
        private readonly ILogger<DeclaracionService> _logger;
        private readonly ILogStore _log_store;
        private const string BASE_URL = "https://api.sat-go.com/api/v2";

        public DeclaracionService(HttpClient http_client, ILogger<DeclaracionService> logger, ILogStore log_store)
        {
            _http_client = http_client;
            _logger = logger;
            _log_store = log_store;
        }

        // -------------------------------------------------------------------------
        // FIEL
        // -------------------------------------------------------------------------

        public async Task<DeclaracionResponse> DescargarDecFielAsync(DeclaracionFielViewModel model)
        {
            _log_store.Add("INFO", "DeclaracionService", "Iniciando descarga Declaración (FIEL)", new
            {
                rfc            = model.Rfc,
                ejercicio      = model.Ejercicio,
                mes            = model.Mes,
                tipo_documento = model.TipoDocumento,
                request_id     = model.RequestId,
                tiene_key      = model.LlavePrivada != null,
                tiene_cer      = model.Certificado != null,
                token_preview  = TruncateToken(model.Authorization)
            });

            try
            {
                var query = BuildQuery(new Dictionary<string, string?>
                {
                    ["ejercicio"]      = model.Ejercicio.ToString(),
                    ["mes"]            = model.Mes.ToString(),
                    ["tipoDocumento"]  = model.TipoDocumento,
                    ["requestId"]      = model.RequestId
                });

                var url = $"{BASE_URL}/Consultar/decfiel{query}";
                _log_store.Add("INFO", "DeclaracionService", "→ POST (FIEL)", new { url });

                using var form_content = new MultipartFormDataContent();
                form_content.Add(new StringContent(model.Contrasena), "Contrasena");

                if (model.LlavePrivada != null)
                {
                    var s = new StreamContent(model.LlavePrivada.OpenReadStream());
                    s.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(s, "llavePrivada", model.LlavePrivada.FileName);
                    _log_store.Add("DEBUG", "DeclaracionService", "Adjuntando llave privada",
                        new { name = model.LlavePrivada.FileName, size = model.LlavePrivada.Length });
                }

                if (model.Certificado != null)
                {
                    var s = new StreamContent(model.Certificado.OpenReadStream());
                    s.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(s, "Certificado", model.Certificado.FileName);
                    _log_store.Add("DEBUG", "DeclaracionService", "Adjuntando certificado",
                        new { name = model.Certificado.FileName, size = model.Certificado.Length });
                }

                using var request = new HttpRequestMessage(HttpMethod.Post, url);
                request.Headers.Add("RFC", model.Rfc);
                request.Headers.Add("Authorization", $"Bearer {model.Authorization}");
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));
                request.Content = form_content;

                var response = await _http_client.SendAsync(request);
                return await ParseResponse(response, "FIEL");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al descargar Declaración FIEL");
                _log_store.Add("ERROR", "DeclaracionService", "Excepción (FIEL)", new { error = ex.Message });
                return new DeclaracionResponse { Success = false, Error = ex.Message, Message = "Error al realizar la descarga" };
            }
        }

        // -------------------------------------------------------------------------
        // CIEC
        // -------------------------------------------------------------------------

        public async Task<DeclaracionResponse> DescargarDecCiecAsync(DeclaracionCiecViewModel model)
        {
            _log_store.Add("INFO", "DeclaracionService", "Iniciando descarga Declaración (CIEC)", new
            {
                rfc           = model.Rfc,
                ejercicio     = model.Ejercicio,
                mes           = model.Mes,
                request_id    = model.RequestId,
                token_preview = TruncateToken(model.Authorization),
                secret_preview= TruncateToken(model.Ciec)
            });

            try
            {
                var query = BuildQuery(new Dictionary<string, string?>
                {
                    ["ejercicio"]  = model.Ejercicio.ToString(),
                    ["mes"]        = model.Mes.ToString(),
                    ["requestId"]  = model.RequestId
                });

                var url = $"{BASE_URL}/Consultar/dec{query}";
                _log_store.Add("INFO", "DeclaracionService", "→ GET (CIEC)", new { url });

                using var request = new HttpRequestMessage(HttpMethod.Get, url);
                request.Headers.Add("RFC", model.Rfc);
                request.Headers.Add("Authorization", $"Bearer {model.Authorization}");
                request.Headers.Add("Secret", model.Ciec);
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));

                var response = await _http_client.SendAsync(request);
                return await ParseResponse(response, "CIEC");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al descargar Declaración CIEC");
                _log_store.Add("ERROR", "DeclaracionService", "Excepción (CIEC)", new { error = ex.Message });
                return new DeclaracionResponse { Success = false, Error = ex.Message, Message = "Error al realizar la descarga" };
            }
        }

        // -------------------------------------------------------------------------
        // Helpers
        // -------------------------------------------------------------------------

        private async Task<DeclaracionResponse> ParseResponse(HttpResponseMessage response, string metodo)
        {
            var content_type = response.Content.Headers.ContentType?.MediaType ?? "application/octet-stream";
            var status       = (int)response.StatusCode;

            _log_store.Add(response.IsSuccessStatusCode ? "INFO" : "ERROR", "DeclaracionService",
                $"← Respuesta ({metodo}) HTTP {status}",
                new { status, content_type });

            if (response.IsSuccessStatusCode)
            {
                var bytes     = await response.Content.ReadAsByteArrayAsync();
                var file_name = response.Content.Headers.ContentDisposition?.FileName?.Trim('"') ?? "declaracion.zip";

                _log_store.Add("INFO", "DeclaracionService", $"Archivo ({metodo}) recibido",
                    new { file_name, bytes = bytes.Length, content_type });

                // Intentar extraer el requestId del header de respuesta (si la API lo devuelve)
                string? request_id = null;
                if (response.Headers.TryGetValues("X-RequestId", out var vals))
                    request_id = vals.FirstOrDefault();

                return new DeclaracionResponse
                {
                    Success     = true,
                    FileData    = bytes,
                    FileName    = file_name,
                    ContentType = content_type,
                    RequestId   = request_id,
                    Message     = "Declaración descargada exitosamente"
                };
            }

            // Error — puede ser JSON con detalles de límite excedido
            var raw = await response.Content.ReadAsStringAsync();
            _logger.LogError("Error descarga Declaración {Metodo}: {Status} - {Content}", metodo, status, raw);
            _log_store.Add("ERROR", "DeclaracionService", $"Body de error ({metodo})",
                new { status, body_preview = raw.Length > 300 ? raw[..300] + "..." : raw });

            var error_msg = ExtractErrorMessage(raw, status);

            return new DeclaracionResponse
            {
                Success = false,
                Error   = error_msg,
                Message = $"Error {status}: {response.ReasonPhrase}"
            };
        }

        private static string BuildQuery(Dictionary<string, string?> params_dict)
        {
            var parts = params_dict
                .Where(p => !string.IsNullOrWhiteSpace(p.Value))
                .Select(p => $"{p.Key}={Uri.EscapeDataString(p.Value!)}");

            var qs = string.Join("&", parts);
            return qs.Length > 0 ? "?" + qs : string.Empty;
        }

        private static string ExtractErrorMessage(string raw, int http_code)
        {
            try
            {
                using var doc = System.Text.Json.JsonDocument.Parse(raw);
                var root = doc.RootElement;
                foreach (var field in new[] { "message", "title", "detail" })
                {
                    if (root.TryGetProperty(field, out var p) && p.ValueKind == System.Text.Json.JsonValueKind.String)
                        return p.GetString() ?? $"Error HTTP {http_code}";
                }
            }
            catch { }

            return string.IsNullOrWhiteSpace(raw) ? $"Error HTTP {http_code}" : raw.Trim();
        }

        private static string TruncateToken(string? token) =>
            string.IsNullOrEmpty(token) ? "(vacío)" : token[..Math.Min(20, token.Length)] + "...";
    }
}
