// Generated by Copilot
using System.Net.Http.Headers;
using System.Text.Json;
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    /// <summary>
    /// Implementación del servicio de consulta de facturas
    /// </summary>
    public class FacturaService : IFacturaService
    {
        private readonly HttpClient _http_client;
        private readonly ILogger<FacturaService> _logger;
        private const string BASE_URL = "https://api.sat-go.com/api/v2";

        public FacturaService(HttpClient http_client, ILogger<FacturaService> logger)
        {
            _http_client = http_client;
            _logger = logger;
        }

        public async Task<FacturaResponse> ConsultarFacturasAsync(ConsultaFacturaViewModel model)
        {
            try
            {
                // Crear el contenido multipart/form-data
                using var form_content = new MultipartFormDataContent();

                // Agregar llave privada si existe
                if (model.LlavePrivada != null)
                {
                    var llave_stream = new StreamContent(model.LlavePrivada.OpenReadStream());
                    llave_stream.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(llave_stream, "llavePrivada", model.LlavePrivada.FileName);
                }

                // Agregar certificado si existe
                if (model.Certificado != null)
                {
                    var cert_stream = new StreamContent(model.Certificado.OpenReadStream());
                    cert_stream.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(cert_stream, "Certificado", model.Certificado.FileName);
                }

                // Agregar contraseña
                form_content.Add(new StringContent(model.Contrasena), "Contrasena");

                // Construir query parameters
                var fecha_inicial = FormatFechaParaApi(model.FechaInicial);
                var fecha_final = FormatFechaParaApi(model.FechaFinal);

                var query_params = new Dictionary<string, string>
                {
                    { "tipoBusqueda", model.TipoBusqueda.ToString() },
                    { "estatusFactura", model.EstatusFactura.ToString() },
                    { "fecha_inicial", fecha_inicial },
                    { "tipo", model.Tipo },
                    { "descargaComprobantes", model.DescargaComprobantes.ToString().ToUpper() },
                    { "fecha_final", fecha_final }
                };

                // Agregar requestId si existe
                if (!string.IsNullOrWhiteSpace(model.RequestId))
                {
                    query_params.Add("requestId", model.RequestId);
                }

                var query_string = string.Join("&", query_params.Select(p => $"{p.Key}={Uri.EscapeDataString(p.Value)}"));
                var url = $"{BASE_URL}/Consultar/facfiel?{query_string}";

                // Crear la solicitud HTTP
                using var request = new HttpRequestMessage(HttpMethod.Post, url);
                request.Headers.Add("RFC", model.Rfc);
                request.Headers.Add("Authorization", $"Bearer {model.Authorization}");
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));
                request.Content = form_content;

                // Enviar la solicitud
                var response = await _http_client.SendAsync(request);
                var response_content = await response.Content.ReadAsStringAsync();

                if (response.IsSuccessStatusCode)
                {
                    var data = JsonSerializer.Deserialize<JsonElement>(response_content);
                    
                    // Intentar obtener el requestId de la respuesta
                    string? request_id = null;
                    if (data.TryGetProperty("requestId", out var request_id_element))
                    {
                        request_id = request_id_element.GetString();
                    }

                    return new FacturaResponse
                    {
                        Success = true,
                        Data = data,
                        Message = "Consulta realizada exitosamente",
                        RequestId = request_id
                    };
                }
                else
                {
                    _logger.LogError("Error en consulta de facturas: {StatusCode} - {Content}", 
                        response.StatusCode, response_content);

                    return new FacturaResponse
                    {
                        Success = false,
                        Error = response_content,
                        Message = $"Error {(int)response.StatusCode}: {response.ReasonPhrase}"
                    };
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al consultar facturas");

                return new FacturaResponse
                {
                    Success = false,
                    Error = ex.Message,
                    Message = "Error al realizar la consulta"
                };
            }
        }

        /// <summary>
        /// Convierte fecha ISO a formato requerido por la API
        /// </summary>
        private static string FormatFechaParaApi(string fecha_iso)
        {
            // Convertir de 2025-10-02T01:30:59 a 2025-10-02 01:30:59
            var fecha_con_espacio = fecha_iso.Replace('T', ' ');
            
            // Si no tiene segundos, agregarlos
            if (fecha_con_espacio.Length == 16) // yyyy-mm-dd hh:mm
            {
                return fecha_con_espacio + ":00";
            }
            
            return fecha_con_espacio;
        }
    }
}
