// Generated by Copilot
namespace SatGoCliente.Services
{
    /// <summary>
    /// Interface para el servicio de autenticación SAT-GO
    /// </summary>
    public interface IAuthService
    {
        Task<CreateKeyResponse> CreateKeyAsync(string tokenPortal);
        Task<GenerarTokenResponse> GenerarTokenAsync(string apiKey);
    }

    public class CreateKeyResponse
    {
        public bool Success { get; set; }
        public string? Key { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
        public string? RawResponse { get; set; }
    }

    public class GenerarTokenResponse
    {
        public bool Success { get; set; }
        public string? AccessToken { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
        public string? RawResponse { get; set; }
    }
}
