// Generated by Copilot
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    public interface ICsfService
    {
        Task<CsfResponse> DescargarCsfAsync(OpinionCumplimientoViewModel model);
        Task<CsfResponse> DescargarCsfCiecAsync(ConsultaCiecViewModel model);
    }

    public class CsfResponse
    {
        public bool Success { get; set; }
        public byte[]? PdfData { get; set; }
        public string? FileName { get; set; }
        public string? ContentType { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
    }
}
