// Generated by Copilot
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    /// <summary>
    /// Interface para el servicio de Constancia de Situación Fiscal
    /// </summary>
    public interface ICsfService
    {
        Task<CsfResponse> DescargarCsfAsync(OpinionCumplimientoViewModel model);
    }

    /// <summary>
    /// Respuesta del servicio de CSF
    /// </summary>
    public class CsfResponse
    {
        public bool Success { get; set; }
        public byte[]? PdfData { get; set; }
        public string? FileName { get; set; }
        public string? ContentType { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
    }
}
