// Generated by Copilot
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    public interface IDeclaracionService
    {
        Task<DeclaracionResponse> DescargarDecFielAsync(DeclaracionFielViewModel model);
        Task<DeclaracionResponse> DescargarDecCiecAsync(DeclaracionCiecViewModel model);
    }

    public class DeclaracionResponse
    {
        public bool Success { get; set; }
        public byte[]? FileData { get; set; }
        public string? FileName { get; set; }
        public string? ContentType { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
        /// <summary>RequestId de sesión para reutilizar en llamadas posteriores.</summary>
        public string? RequestId { get; set; }
    }
}
