// Generated by Copilot
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    /// <summary>
    /// Interface para el servicio de consulta de facturas
    /// </summary>
    public interface IFacturaService
    {
        Task<FacturaResponse> ConsultarFacturasAsync(ConsultaFacturaViewModel model);
    }

    /// <summary>
    /// Respuesta del servicio de facturas
    /// </summary>
    public class FacturaResponse
    {
        public bool Success { get; set; }
        public object? Data { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
        public string? RequestId { get; set; }
    }
}
