// Generated by Copilot
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    public interface IInfoFiscalService
    {
        Task<InfoFiscalResponse> ConsultarFielAsync(InfoFiscalFielViewModel model);
        Task<InfoFiscalResponse> ConsultarCiecAsync(InfoFiscalCiecViewModel model);
    }

    public class InfoFiscalResponse
    {
        public bool Success { get; set; }
        public object? Data { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
        public string? RequestId { get; set; }
    }
}
