// Generated by Copilot
using System.Collections.Concurrent;
using System.Text.Json;

namespace SatGoCliente.Services
{
    public class LogEntry
    {
        public DateTime Timestamp { get; set; }
        public string Level { get; set; } = string.Empty;
        public string Service { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public string? Details { get; set; }
    }

    public interface ILogStore
    {
        void Add(string level, string service, string message, object? details = null);
        IReadOnlyList<LogEntry> GetAll();
        void Clear();
    }

    /// <summary>
    /// Almacén de logs en memoria (singleton). Guarda los últimos 200 eventos para
    /// mostrarlos en el panel de trazas de la UI sin necesidad de leer archivos de disco.
    /// </summary>
    public class LogStore : ILogStore
    {
        private readonly ConcurrentQueue<LogEntry> _entries = new();
        private const int MaxEntries = 200;

        public void Add(string level, string service, string message, object? details = null)
        {
            _entries.Enqueue(new LogEntry
            {
                Timestamp = DateTime.Now,
                Level = level,
                Service = service,
                Message = message,
                Details = details is null ? null
                    : details is string s ? s
                    : JsonSerializer.Serialize(details, new JsonSerializerOptions { WriteIndented = false })
            });

            // Mantener tamaño máximo (FIFO)
            while (_entries.Count > MaxEntries)
                _entries.TryDequeue(out _);
        }

        public IReadOnlyList<LogEntry> GetAll() => _entries.ToArray();

        public void Clear()
        {
            while (_entries.TryDequeue(out _)) { }
        }
    }
}
