// Generated by Copilot
using System.Net.Http.Headers;
using System.Text.Json;
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    /// <summary>
    /// Servicio de Información Fiscal SAT.
    ///
    /// FIEL: POST /api/v2/Consultar/informacionfiscalfiel
    ///       Query: requestId (opcional)
    ///       Body:  multipart — Contrasena, llavePrivada, Certificado
    ///       Headers: RFC, Authorization: Bearer
    ///
    /// CIEC: GET  /api/v2/Consultar/informacionfiscal
    ///       Query: requestId (opcional)
    ///       Headers: RFC, Authorization: Bearer, Secret: {ciec}
    ///
    /// Respuesta: JSON con la información fiscal del contribuyente.
    /// </summary>
    public class InfoFiscalService : IInfoFiscalService
    {
        private readonly HttpClient _http_client;
        private readonly ILogger<InfoFiscalService> _logger;
        private readonly ILogStore _log_store;
        private const string BASE_URL = "https://api.sat-go.com/api/v2";

        public InfoFiscalService(HttpClient http_client, ILogger<InfoFiscalService> logger, ILogStore log_store)
        {
            _http_client = http_client;
            _logger = logger;
            _log_store = log_store;
        }

        // -------------------------------------------------------------------------
        // FIEL
        // -------------------------------------------------------------------------

        public async Task<InfoFiscalResponse> ConsultarFielAsync(InfoFiscalFielViewModel model)
        {
            _log_store.Add("INFO", "InfoFiscalService", "Iniciando consulta Información Fiscal (FIEL)", new
            {
                rfc           = model.Rfc,
                request_id    = model.RequestId,
                tiene_key     = model.LlavePrivada != null,
                tiene_cer     = model.Certificado != null,
                token_preview = TruncateToken(model.Authorization)
            });

            try
            {
                var qs  = string.IsNullOrWhiteSpace(model.RequestId) ? "" : $"?requestId={Uri.EscapeDataString(model.RequestId)}";
                var url = $"{BASE_URL}/Consultar/informacionfiscalfiel{qs}";
                _log_store.Add("INFO", "InfoFiscalService", "→ POST (FIEL)", new { url });

                using var form_content = new MultipartFormDataContent();
                form_content.Add(new StringContent(model.Contrasena), "Contrasena");

                if (model.LlavePrivada != null)
                {
                    var s = new StreamContent(model.LlavePrivada.OpenReadStream());
                    s.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(s, "llavePrivada", model.LlavePrivada.FileName);
                    _log_store.Add("DEBUG", "InfoFiscalService", "Adjuntando llave privada",
                        new { name = model.LlavePrivada.FileName, size = model.LlavePrivada.Length });
                }

                if (model.Certificado != null)
                {
                    var s = new StreamContent(model.Certificado.OpenReadStream());
                    s.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(s, "Certificado", model.Certificado.FileName);
                    _log_store.Add("DEBUG", "InfoFiscalService", "Adjuntando certificado",
                        new { name = model.Certificado.FileName, size = model.Certificado.Length });
                }

                using var request = new HttpRequestMessage(HttpMethod.Post, url);
                request.Headers.Add("RFC", model.Rfc);
                request.Headers.Add("Authorization", $"Bearer {model.Authorization}");
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));
                request.Content = form_content;

                var response = await _http_client.SendAsync(request);
                return await ParseResponse(response, "FIEL");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al consultar Información Fiscal FIEL");
                _log_store.Add("ERROR", "InfoFiscalService", "Excepción (FIEL)", new { error = ex.Message });
                return new InfoFiscalResponse { Success = false, Error = ex.Message, Message = "Error al realizar la consulta" };
            }
        }

        // -------------------------------------------------------------------------
        // CIEC
        // -------------------------------------------------------------------------

        public async Task<InfoFiscalResponse> ConsultarCiecAsync(InfoFiscalCiecViewModel model)
        {
            _log_store.Add("INFO", "InfoFiscalService", "Iniciando consulta Información Fiscal (CIEC)", new
            {
                rfc            = model.Rfc,
                request_id     = model.RequestId,
                token_preview  = TruncateToken(model.Authorization),
                secret_preview = TruncateToken(model.Ciec)
            });

            try
            {
                var qs  = string.IsNullOrWhiteSpace(model.RequestId) ? "" : $"?requestId={Uri.EscapeDataString(model.RequestId)}";
                var url = $"{BASE_URL}/Consultar/informacionfiscal{qs}";
                _log_store.Add("INFO", "InfoFiscalService", "→ GET (CIEC)", new { url });

                using var request = new HttpRequestMessage(HttpMethod.Get, url);
                request.Headers.Add("RFC", model.Rfc);
                request.Headers.Add("Authorization", $"Bearer {model.Authorization}");
                request.Headers.Add("Secret", model.Ciec);
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));

                var response = await _http_client.SendAsync(request);
                return await ParseResponse(response, "CIEC");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al consultar Información Fiscal CIEC");
                _log_store.Add("ERROR", "InfoFiscalService", "Excepción (CIEC)", new { error = ex.Message });
                return new InfoFiscalResponse { Success = false, Error = ex.Message, Message = "Error al realizar la consulta" };
            }
        }

        // -------------------------------------------------------------------------

        private async Task<InfoFiscalResponse> ParseResponse(HttpResponseMessage response, string metodo)
        {
            var status = (int)response.StatusCode;
            var raw    = await response.Content.ReadAsStringAsync();

            _log_store.Add(response.IsSuccessStatusCode ? "INFO" : "ERROR", "InfoFiscalService",
                $"← Respuesta ({metodo}) HTTP {status}",
                new { status, body_size = raw.Length, body_preview = Truncate(raw, 300) });

            if (response.IsSuccessStatusCode)
            {
                var data       = JsonSerializer.Deserialize<JsonElement>(raw);
                string? req_id = null;
                if (data.TryGetProperty("requestId", out var rid)) req_id = rid.GetString();

                return new InfoFiscalResponse { Success = true, Data = data, RequestId = req_id, Message = "Información Fiscal obtenida exitosamente" };
            }

            _logger.LogError("Error Información Fiscal {Metodo}: {Status} - {Content}", metodo, status, raw);

            string error_msg;
            try
            {
                using var doc = JsonDocument.Parse(raw);
                var root = doc.RootElement;
                error_msg = new[] { "message", "title", "detail" }
                    .Select(f => root.TryGetProperty(f, out var p) && p.ValueKind == JsonValueKind.String ? p.GetString() : null)
                    .FirstOrDefault(v => v != null) ?? $"Error HTTP {status}";
            }
            catch { error_msg = string.IsNullOrWhiteSpace(raw) ? $"Error HTTP {status}" : raw.Trim(); }

            return new InfoFiscalResponse { Success = false, Error = error_msg, Message = $"Error {status}: {response.ReasonPhrase}" };
        }

        private static string TruncateToken(string? t) =>
            string.IsNullOrEmpty(t) ? "(vacío)" : t[..Math.Min(20, t.Length)] + "...";

        private static string Truncate(string s, int max) =>
            s.Length <= max ? s : s[..max] + $"... (+{s.Length - max} chars)";
    }
}
