// Generated by Copilot
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    public interface IOpinionCumplimientoService
    {
        Task<OpinionCumplimientoResponse> DescargarOpinionAsync(OpinionCumplimientoViewModel model);
        Task<OpinionCumplimientoResponse> DescargarOpinionCiecAsync(ConsultaCiecViewModel model);
    }

    public class OpinionCumplimientoResponse
    {
        public bool Success { get; set; }
        public byte[]? PdfData { get; set; }
        public string? FileName { get; set; }
        public string? ContentType { get; set; }
        public string? Message { get; set; }
        public string? Error { get; set; }
    }
}
