// Generated by Copilot
using System.Net.Http.Headers;
using SatGoCliente.Models;

namespace SatGoCliente.Services
{
    /// <summary>
    /// Implementación del servicio de Opinión de Cumplimiento
    /// </summary>
    public class OpinionCumplimientoService : IOpinionCumplimientoService
    {
        private readonly HttpClient _http_client;
        private readonly ILogger<OpinionCumplimientoService> _logger;
        private const string BASE_URL = "https://api.sat-go.com/api/v2";

        public OpinionCumplimientoService(HttpClient http_client, ILogger<OpinionCumplimientoService> logger)
        {
            _http_client = http_client;
            _logger = logger;
        }

        public async Task<OpinionCumplimientoResponse> DescargarOpinionAsync(OpinionCumplimientoViewModel model)
        {
            try
            {
                // Crear el contenido multipart/form-data
                using var form_content = new MultipartFormDataContent();

                // Agregar llave privada si existe
                if (model.LlavePrivada != null)
                {
                    var llave_stream = new StreamContent(model.LlavePrivada.OpenReadStream());
                    llave_stream.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(llave_stream, "llavePrivada", model.LlavePrivada.FileName);
                }

                // Agregar certificado si existe
                if (model.Certificado != null)
                {
                    var cert_stream = new StreamContent(model.Certificado.OpenReadStream());
                    cert_stream.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
                    form_content.Add(cert_stream, "Certificado", model.Certificado.FileName);
                }

                // Agregar contraseña
                form_content.Add(new StringContent(model.Contrasena), "Contrasena");

                var url = $"{BASE_URL}/Consultar/ocfiel";

                // Crear la solicitud HTTP
                using var request = new HttpRequestMessage(HttpMethod.Post, url);
                request.Headers.Add("RFC", model.Rfc);
                request.Headers.Add("Authorization", $"Bearer {model.Authorization}");
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*"));
                request.Content = form_content;

                // Enviar la solicitud
                var response = await _http_client.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    var content_type = response.Content.Headers.ContentType?.MediaType ?? "application/pdf";
                    var pdf_bytes = await response.Content.ReadAsByteArrayAsync();
                    
                    // Obtener nombre del archivo del header Content-Disposition
                    var file_name = "OpinionDeCumplimiento.pdf";
                    if (response.Content.Headers.ContentDisposition?.FileName != null)
                    {
                        file_name = response.Content.Headers.ContentDisposition.FileName.Trim('"');
                    }

                    return new OpinionCumplimientoResponse
                    {
                        Success = true,
                        PdfData = pdf_bytes,
                        FileName = file_name,
                        ContentType = content_type,
                        Message = "Opinión de Cumplimiento descargada exitosamente"
                    };
                }
                else
                {
                    var error_content = await response.Content.ReadAsStringAsync();
                    _logger.LogError("Error en descarga de Opinión de Cumplimiento: {StatusCode} - {Content}", 
                        response.StatusCode, error_content);

                    return new OpinionCumplimientoResponse
                    {
                        Success = false,
                        Error = error_content,
                        Message = $"Error {(int)response.StatusCode}: {response.ReasonPhrase}"
                    };
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al descargar Opinión de Cumplimiento");

                return new OpinionCumplimientoResponse
                {
                    Success = false,
                    Error = ex.Message,
                    Message = "Error al realizar la descarga"
                };
            }
        }
    }
}
