<?php
// Generated by Copilot

require_once __DIR__ . '/config/api.php';
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consulta de Facturas SAT - Cliente PHP</title>
    <link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>
    <!-- Generated by Copilot - Navbar -->
    <nav class="navbar">
        <span class="navbar-brand">SAT-GO Cliente</span>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" onclick="showSection('facturas', this)">&#128196; Descarga de Facturas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" onclick="showSection('csf', this)">&#128203; Descarga de CSF</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" onclick="showSection('oc', this)">&#9989; Opinión de Cumplimiento</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" onclick="showSection('dec', this)">&#128196; Declaraciones</a>
            </li>
        </ul>
    </nav>

    <div class="container">

        <!-- ======================== SECCIÓN: FACTURAS ======================== -->
        <div id="section-facturas" class="page-section active">

        <!-- Formulario de Consulta -->
        <div class="card">
            <div class="card-header">
                <h2>Consulta de Facturas FIEL</h2>
            </div>
            <div class="card-body">
                <!-- Alert Container -->
                <div id="alertContainer"></div>

                <form id="consultaForm" enctype="multipart/form-data">
                    <!-- Datos FIEL -->
                    <div class="row mb-3">
                        <div class="col">
                            <h5>Información FIEL</h5>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label" for="rfc">RFC</label>
                                <input type="text" class="form-control" id="rfc" name="rfc" 
                                       value="<?= htmlspecialchars(FormDefaults::RFC) ?>" 
                                       placeholder="RFC del contribuyente" required>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label" for="authorization">Token de Autorización</label>
                                <textarea class="form-control" id="authorization" name="authorization" 
                                          rows="3" placeholder="Bearer token de autorización" required></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label" for="request_id">Request ID (Opcional - para reusar sesión)</label>
                                <input type="text" class="form-control" id="request_id" name="request_id" 
                                       placeholder="ID de request para mantener la sesión activa">
                                <small class="form-text">Si tienes un Request ID de una consulta anterior, ingrésalo aquí para reusar la sesión.</small>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="llave_privada">Llave Privada (.key)</label>
                                <input type="file" class="form-control" id="llave_privada" name="llave_privada" accept=".key">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="certificado">Certificado (.cer)</label>
                                <input type="file" class="form-control" id="certificado" name="certificado" accept=".cer">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="contrasena">Contraseña de la Llave Privada</label>
                                <input type="password" class="form-control" id="contrasena" name="contrasena" 
                                       value="<?= htmlspecialchars(FormDefaults::CONTRASENA) ?>" 
                                       placeholder="Contraseña de la FIEL" required>
                            </div>
                        </div>
                    </div>

                    <!-- Parámetros de consulta -->
                    <div class="row mb-3">
                        <div class="col">
                            <h5>Parámetros de Consulta</h5>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="tipo_busqueda">Tipo de Búsqueda</label>
                                <select class="form-select" id="tipo_busqueda" name="tipo_busqueda">
                                    <option value="1" <?= FormDefaults::TIPO_BUSQUEDA === 1 ? 'selected' : '' ?>>Por Fecha</option>
                                    <option value="2" <?= FormDefaults::TIPO_BUSQUEDA === 2 ? 'selected' : '' ?>>Por Folio</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="estatus_factura">Estatus Factura</label>
                                <select class="form-select" id="estatus_factura" name="estatus_factura">
                                    <option value="-1" <?= FormDefaults::ESTATUS_FACTURA === -1 ? 'selected' : '' ?>>Todos</option>
                                    <option value="1" <?= FormDefaults::ESTATUS_FACTURA === 1 ? 'selected' : '' ?>>Vigente</option>
                                    <option value="0" <?= FormDefaults::ESTATUS_FACTURA === 0 ? 'selected' : '' ?>>Cancelada</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="tipo">Tipo</label>
                                <select class="form-select" id="tipo" name="tipo">
                                    <option value="recibidos" <?= FormDefaults::TIPO === 'recibidos' ? 'selected' : '' ?>>Recibidos</option>
                                    <option value="emitidos" <?= FormDefaults::TIPO === 'emitidos' ? 'selected' : '' ?>>Emitidos</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="form-label" for="fecha_inicial">Fecha Inicial</label>
                                <input type="datetime-local" class="form-control" id="fecha_inicial" name="fecha_inicial" 
                                       value="<?= htmlspecialchars(FormDefaults::FECHA_INICIAL) ?>" step="1" required>
                                <small class="form-text" id="fecha_inicial_preview">Formato enviado: </small>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="form-label" for="fecha_final">Fecha Final</label>
                                <input type="datetime-local" class="form-control" id="fecha_final" name="fecha_final" 
                                       value="<?= htmlspecialchars(FormDefaults::FECHA_FINAL) ?>" step="1" required>
                                <small class="form-text" id="fecha_final_preview">Formato enviado: </small>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="form-label">Descargar Comprobantes</label>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="descarga_comprobantes" 
                                           name="descarga_comprobantes" <?= FormDefaults::DESCARGA_COMPROBANTES ? 'checked' : '' ?>>
                                    <label class="form-check-label" for="descarga_comprobantes">Sí</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col d-grid">
                            <button type="submit" class="btn btn-primary btn-lg" id="submitBtn">
                                <span id="btnText">Consultar Facturas</span>
                                <span id="btnSpinner" class="hidden"><span class="spinner me-2"></span>Consultando...</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- Resultados -->
        <div class="card mt-4" id="resultadosCard" style="display: none;">
            <div class="card-header">
                <div class="results-header">
                    <div>
                        <h2>Resultados de la Consulta</h2>
                        <small class="text-muted" id="requestIdDisplay"></small>
                        <small class="text-muted" id="paginationInfo"></small>
                    </div>
                    <div>
                        <span class="badge badge-primary" id="totalFacturas">0 factura(s) encontrada(s)</span>
                        <span class="badge badge-success" id="statusBadge">Éxito</span>
                        <!-- Generated by Copilot - Botón descargar todos -->
                        <button class="btn btn-download-all btn-sm" id="downloadAllBtn" style="display: none;" onclick="downloadAllXMLs()">
                            <span class="download-icon">⬇</span> Descargar Todos los XML
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div id="resultadosContent"></div>
            </div>
        </div>

        </div><!-- /section-facturas -->

        <!-- ======================== SECCIÓN: CSF ======================== -->
        <!-- Generated by Copilot - Sección Descarga de CSF -->
        <div id="section-csf" class="page-section">

            <!-- Formulario CSF -->
            <div class="card">
                <div class="card-header">
                    <h2>Descarga de Constancia de Situación Fiscal (CSF)</h2>
                </div>
                <div class="card-body">

                    <div id="csf-alertContainer"></div>

                    <form id="csfForm" enctype="multipart/form-data">

                        <!-- Información FIEL -->
                        <div class="row mb-3">
                            <div class="col">
                                <h5>Información FIEL</h5>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="form-label" for="csf_rfc">RFC</label>
                                    <input type="text" class="form-control" id="csf_rfc" name="csf_rfc"
                                           value="<?= htmlspecialchars(FormDefaults::RFC) ?>"
                                           placeholder="RFC del contribuyente" required>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="form-label" for="csf_authorization">Token de Autorización</label>
                                    <textarea class="form-control" id="csf_authorization" name="csf_authorization"
                                              rows="3" placeholder="Bearer token de autorización" required></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="csf_llave_privada">Llave Privada (.key)</label>
                                    <input type="file" class="form-control" id="csf_llave_privada"
                                           name="csf_llave_privada" accept=".key">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="csf_certificado">Certificado (.cer)</label>
                                    <input type="file" class="form-control" id="csf_certificado"
                                           name="csf_certificado" accept=".cer">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="csf_contrasena">Contraseña de la Llave Privada</label>
                                    <input type="password" class="form-control" id="csf_contrasena"
                                           name="csf_contrasena"
                                           value="<?= htmlspecialchars(FormDefaults::CONTRASENA) ?>"
                                           placeholder="Contraseña de la FIEL" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col d-grid">
                                <button type="submit" class="btn btn-primary btn-lg" id="csfSubmitBtn">
                                    <span id="csfBtnText">Descargar CSF</span>
                                    <span id="csfBtnSpinner" class="hidden"><span class="spinner me-2"></span>Descargando...</span>
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

            <!-- Resultado CSF -->
            <div class="card mt-4" id="csfResultadoCard" style="display: none;">
                <div class="card-header">
                    <h2>Resultado de la Descarga</h2>
                </div>
                <div class="card-body">
                    <div id="csfResultadoContent"></div>
                </div>
            </div>

        </div><!-- /section-csf -->

        <!-- ======================== SECCIÓN: OPINIÓN DE CUMPLIMIENTO ======================== -->
        <!-- Generated by Copilot - Sección Opinión de Cumplimiento -->
        <div id="section-oc" class="page-section">

            <div class="card">
                <div class="card-header">
                    <h2>Opinión de Cumplimiento (OC)</h2>
                </div>
                <div class="card-body">

                    <div id="oc-alertContainer"></div>

                    <form id="ocForm" enctype="multipart/form-data">

                        <div class="row mb-3">
                            <div class="col">
                                <h5>Información FIEL</h5>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="form-label" for="oc_rfc">RFC</label>
                                    <input type="text" class="form-control" id="oc_rfc" name="oc_rfc"
                                           value="<?= htmlspecialchars(FormDefaults::RFC) ?>"
                                           placeholder="RFC del contribuyente" required>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="form-label" for="oc_authorization">Token de Autorización</label>
                                    <textarea class="form-control" id="oc_authorization" name="oc_authorization"
                                              rows="3" placeholder="Bearer token de autorización" required></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="oc_llave_privada">Llave Privada (.key)</label>
                                    <input type="file" class="form-control" id="oc_llave_privada"
                                           name="oc_llave_privada" accept=".key">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="oc_certificado">Certificado (.cer)</label>
                                    <input type="file" class="form-control" id="oc_certificado"
                                           name="oc_certificado" accept=".cer">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="oc_contrasena">Contraseña de la Llave Privada</label>
                                    <input type="password" class="form-control" id="oc_contrasena"
                                           name="oc_contrasena"
                                           value="<?= htmlspecialchars(FormDefaults::CONTRASENA) ?>"
                                           placeholder="Contraseña de la FIEL" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col d-grid">
                                <button type="submit" class="btn btn-primary btn-lg" id="ocSubmitBtn">
                                    <span id="ocBtnText">Consultar Opinión de Cumplimiento</span>
                                    <span id="ocBtnSpinner" class="hidden"><span class="spinner me-2"></span>Consultando...</span>
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

            <!-- Resultado OC -->
            <div class="card mt-4" id="ocResultadoCard" style="display: none;">
                <div class="card-header">
                    <h2>Resultado de la Consulta</h2>
                </div>
                <div class="card-body">
                    <div id="ocResultadoContent"></div>
                </div>
            </div>

        </div><!-- /section-oc -->

        <!-- ======================== SECCIÓN: DECLARACIONES ======================== -->
        <!-- Generated by Copilot - Sección Declaraciones -->
        <div id="section-dec" class="page-section">

            <div class="card">
                <div class="card-header">
                    <h2>Descarga de Declaraciones</h2>
                </div>
                <div class="card-body">

                    <div id="dec-alertContainer"></div>

                    <form id="decForm" enctype="multipart/form-data">

                        <!-- Información FIEL -->
                        <div class="row mb-3">
                            <div class="col"><h5>Información FIEL</h5></div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="form-label" for="dec_rfc">RFC</label>
                                    <input type="text" class="form-control" id="dec_rfc" name="dec_rfc"
                                           value="<?= htmlspecialchars(FormDefaults::RFC) ?>"
                                           placeholder="RFC del contribuyente" required>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="form-label" for="dec_authorization">Token de Autorización</label>
                                    <textarea class="form-control" id="dec_authorization" name="dec_authorization"
                                              rows="3" placeholder="Bearer token de autorización" required></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="dec_llave_privada">Llave Privada (.key)</label>
                                    <input type="file" class="form-control" id="dec_llave_privada"
                                           name="dec_llave_privada" accept=".key">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="dec_certificado">Certificado (.cer)</label>
                                    <input type="file" class="form-control" id="dec_certificado"
                                           name="dec_certificado" accept=".cer">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label" for="dec_contrasena">Contraseña de la Llave Privada</label>
                                    <input type="password" class="form-control" id="dec_contrasena"
                                           name="dec_contrasena"
                                           value="<?= htmlspecialchars(FormDefaults::CONTRASENA) ?>"
                                           placeholder="Contraseña de la FIEL" required>
                                </div>
                            </div>
                        </div>

                        <!-- Parámetros de la declaración -->
                        <div class="row mb-3">
                            <div class="col"><h5>Parámetros de la Declaración</h5></div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label" for="dec_ejercicio">Ejercicio</label>
                                    <select class="form-select" id="dec_ejercicio" name="dec_ejercicio" required>
                                        <option value="2024">2024</option>
                                        <option value="2025">2025</option>
                                        <option value="2026" selected>2026</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label" for="dec_mes">Mes</label>
                                    <select class="form-select" id="dec_mes" name="dec_mes" required>
                                        <option value="1">1 - Enero</option>
                                        <option value="2">2 - Febrero</option>
                                        <option value="3">3 - Marzo</option>
                                        <option value="4">4 - Abril</option>
                                        <option value="5">5 - Mayo</option>
                                        <option value="6">6 - Junio</option>
                                        <option value="7">7 - Julio</option>
                                        <option value="8">8 - Agosto</option>
                                        <option value="9">9 - Septiembre</option>
                                        <option value="10">10 - Octubre</option>
                                        <option value="11">11 - Noviembre</option>
                                        <option value="12">12 - Diciembre</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label" for="dec_tipo_documento">Tipo de Documento</label>
                                    <select class="form-select" id="dec_tipo_documento" name="dec_tipo_documento" required>
                                        <option value="pago">Pago</option>
                                        <option value="normal">Normal</option>
                                        <option value="complementaria">Complementaria</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="form-label" for="dec_request_id">Request ID <small class="text-muted">(Opcional)</small></label>
                                    <input type="text" class="form-control" id="dec_request_id" name="dec_request_id"
                                           placeholder="ID de request previo">
                                    <small class="form-text">Para reutilizar una sesión existente.</small>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col d-grid">
                                <button type="submit" class="btn btn-primary btn-lg" id="decSubmitBtn">
                                    <span id="decBtnText">Descargar Declaración</span>
                                    <span id="decBtnSpinner" class="hidden"><span class="spinner me-2"></span>Descargando...</span>
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

            <!-- Resultado Declaración -->
            <div class="card mt-4" id="decResultadoCard" style="display: none;">
                <div class="card-header">
                    <h2>Resultado de la Descarga</h2>
                </div>
                <div class="card-body">
                    <div id="decResultadoContent"></div>
                </div>
            </div>

        </div><!-- /section-dec -->

        <!-- Modal de Error -->
        <div class="modal-backdrop" id="errorModal">
            <div class="modal">
                <div class="modal-header">
                    <h3 id="errorTitle">Error</h3>
                    <button class="modal-close" onclick="closeErrorModal()">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger">
                        <strong>Error</strong>
                        <p id="errorMessage"></p>
                        <details>
                            <summary class="text-muted">Ver detalles técnicos</summary>
                            <pre id="errorDetails"></pre>
                        </details>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" onclick="closeErrorModal()">Cerrar</button>
                    <button class="btn btn-primary" onclick="retrySubmit()">Reintentar</button>
                </div>
            </div>
        </div>

        <!-- Modal de Visualización XML - Generated by Copilot -->
        <div class="xml-modal-backdrop" id="xmlModal">
            <div class="xml-modal">
                <div class="xml-modal-header">
                    <h3 id="xmlModalTitle">Contenido XML</h3>
                    <button class="modal-close" onclick="closeXMLModal()">&times;</button>
                </div>
                <div class="xml-modal-body">
                    <pre class="xml-content" id="xmlModalContent"></pre>
                </div>
                <div class="xml-modal-footer">
                    <button class="btn btn-secondary" onclick="closeXMLModal()">Cerrar</button>
                    <button class="btn btn-success" id="xmlModalDownloadBtn">
                        <span class="download-icon">⬇</span> Descargar XML
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="assets/js/app.js?v=<?= time() ?>"></script>
</body>
</html>
