<?php
// Generated by Copilot

require_once __DIR__ . '/config/api.php';
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consulta de Facturas SAT - Cliente PHP</title>
    <link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>
    <div class="container">
        <!-- Formulario de Consulta -->
        <div class="card">
            <div class="card-header">
                <h2>Consulta de Facturas FIEL</h2>
            </div>
            <div class="card-body">
                <!-- Alert Container -->
                <div id="alertContainer"></div>

                <form id="consultaForm" enctype="multipart/form-data">
                    <!-- Datos FIEL -->
                    <div class="row mb-3">
                        <div class="col">
                            <h5>Información FIEL</h5>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label" for="rfc">RFC</label>
                                <input type="text" class="form-control" id="rfc" name="rfc" 
                                       value="<?= htmlspecialchars(FormDefaults::RFC) ?>" 
                                       placeholder="RFC del contribuyente" required>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label" for="authorization">Token de Autorización</label>
                                <textarea class="form-control" id="authorization" name="authorization" 
                                          rows="3" placeholder="Bearer token de autorización" required></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label" for="request_id">Request ID (Opcional - para reusar sesión)</label>
                                <input type="text" class="form-control" id="request_id" name="request_id" 
                                       placeholder="ID de request para mantener la sesión activa">
                                <small class="form-text">Si tienes un Request ID de una consulta anterior, ingrésalo aquí para reusar la sesión.</small>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="llave_privada">Llave Privada (.key)</label>
                                <input type="file" class="form-control" id="llave_privada" name="llave_privada" accept=".key">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="certificado">Certificado (.cer)</label>
                                <input type="file" class="form-control" id="certificado" name="certificado" accept=".cer">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="contrasena">Contraseña de la Llave Privada</label>
                                <input type="password" class="form-control" id="contrasena" name="contrasena" 
                                       value="<?= htmlspecialchars(FormDefaults::CONTRASENA) ?>" 
                                       placeholder="Contraseña de la FIEL" required>
                            </div>
                        </div>
                    </div>

                    <!-- Parámetros de consulta -->
                    <div class="row mb-3">
                        <div class="col">
                            <h5>Parámetros de Consulta</h5>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="tipo_busqueda">Tipo de Búsqueda</label>
                                <select class="form-select" id="tipo_busqueda" name="tipo_busqueda">
                                    <option value="1" <?= FormDefaults::TIPO_BUSQUEDA === 1 ? 'selected' : '' ?>>Por Fecha</option>
                                    <option value="2" <?= FormDefaults::TIPO_BUSQUEDA === 2 ? 'selected' : '' ?>>Por Folio</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="estatus_factura">Estatus Factura</label>
                                <select class="form-select" id="estatus_factura" name="estatus_factura">
                                    <option value="-1" <?= FormDefaults::ESTATUS_FACTURA === -1 ? 'selected' : '' ?>>Todos</option>
                                    <option value="1" <?= FormDefaults::ESTATUS_FACTURA === 1 ? 'selected' : '' ?>>Vigente</option>
                                    <option value="0" <?= FormDefaults::ESTATUS_FACTURA === 0 ? 'selected' : '' ?>>Cancelada</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label" for="tipo">Tipo</label>
                                <select class="form-select" id="tipo" name="tipo">
                                    <option value="recibidos" <?= FormDefaults::TIPO === 'recibidos' ? 'selected' : '' ?>>Recibidos</option>
                                    <option value="emitidos" <?= FormDefaults::TIPO === 'emitidos' ? 'selected' : '' ?>>Emitidos</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="form-label" for="fecha_inicial">Fecha Inicial</label>
                                <input type="datetime-local" class="form-control" id="fecha_inicial" name="fecha_inicial" 
                                       value="<?= htmlspecialchars(FormDefaults::FECHA_INICIAL) ?>" step="1" required>
                                <small class="form-text" id="fecha_inicial_preview">Formato enviado: </small>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="form-label" for="fecha_final">Fecha Final</label>
                                <input type="datetime-local" class="form-control" id="fecha_final" name="fecha_final" 
                                       value="<?= htmlspecialchars(FormDefaults::FECHA_FINAL) ?>" step="1" required>
                                <small class="form-text" id="fecha_final_preview">Formato enviado: </small>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="form-label">Descargar Comprobantes</label>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="descarga_comprobantes" 
                                           name="descarga_comprobantes" <?= FormDefaults::DESCARGA_COMPROBANTES ? 'checked' : '' ?>>
                                    <label class="form-check-label" for="descarga_comprobantes">Sí</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col d-grid">
                            <button type="submit" class="btn btn-primary btn-lg" id="submitBtn">
                                <span id="btnText">Consultar Facturas</span>
                                <span id="btnSpinner" class="hidden"><span class="spinner me-2"></span>Consultando...</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- Resultados -->
        <div class="card mt-4" id="resultadosCard" style="display: none;">
            <div class="card-header">
                <div class="results-header">
                    <div>
                        <h2>Resultados de la Consulta</h2>
                        <small class="text-muted" id="requestIdDisplay"></small>
                        <small class="text-muted" id="paginationInfo"></small>
                    </div>
                    <div>
                        <span class="badge badge-primary" id="totalFacturas">0 factura(s) encontrada(s)</span>
                        <span class="badge badge-success" id="statusBadge">Éxito</span>
                        <!-- Generated by Copilot - Botón descargar todos -->
                        <button class="btn btn-download-all btn-sm" id="downloadAllBtn" style="display: none;" onclick="downloadAllXMLs()">
                            <span class="download-icon">⬇</span> Descargar Todos los XML
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div id="resultadosContent"></div>
            </div>
        </div>

        <!-- Modal de Error -->
        <div class="modal-backdrop" id="errorModal">
            <div class="modal">
                <div class="modal-header">
                    <h3 id="errorTitle">Error</h3>
                    <button class="modal-close" onclick="closeErrorModal()">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger">
                        <strong>Error</strong>
                        <p id="errorMessage"></p>
                        <details>
                            <summary class="text-muted">Ver detalles técnicos</summary>
                            <pre id="errorDetails"></pre>
                        </details>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" onclick="closeErrorModal()">Cerrar</button>
                    <button class="btn btn-primary" onclick="retrySubmit()">Reintentar</button>
                </div>
            </div>
        </div>

        <!-- Modal de Visualización XML - Generated by Copilot -->
        <div class="xml-modal-backdrop" id="xmlModal">
            <div class="xml-modal">
                <div class="xml-modal-header">
                    <h3 id="xmlModalTitle">Contenido XML</h3>
                    <button class="modal-close" onclick="closeXMLModal()">&times;</button>
                </div>
                <div class="xml-modal-body">
                    <pre class="xml-content" id="xmlModalContent"></pre>
                </div>
                <div class="xml-modal-footer">
                    <button class="btn btn-secondary" onclick="closeXMLModal()">Cerrar</button>
                    <button class="btn btn-success" id="xmlModalDownloadBtn">
                        <span class="download-icon">⬇</span> Descargar XML
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="assets/js/app.js"></script>
</body>
</html>
