// Generated by Copilot
export interface CsfFielRequest {
  rfc: string;
  authorization: string;
  llave_privada?: File;
  certificado?: File;
  contrasena: string;
}

export interface CsfResponse {
  success: boolean;
  data?: Blob;
  message?: string;
  error?: string;
  error_type?: 'json' | 'text';
  error_data?: any;
}
