// Generated by Copilot
export interface ConsultaFacturaParams {
  tipo_busqueda: number;
  estatus_factura: number;
  fecha_inicial: string;
  tipo: 'recibidos' | 'emitidos';
  descarga_comprobantes: boolean;
  fecha_final: string;
}

export interface FacturaFielRequest {
  rfc: string;
  authorization: string;
  llave_privada?: File;
  certificado?: File;
  contrasena: string;
  request_id?: string;
}

export interface FacturaResponse {
  success: boolean;
  data?: any;
  message?: string;
  error?: string;
}