// Generated by Copilot
// Tipos compartidos para datos FIEL usados en múltiples formularios

export interface FielData {
  rfc: string;
  authorization: string;
  contrasena: string;
}

export interface FielFiles {
  llave_privada?: File;
  certificado?: File;
}

export interface FielCompleteData extends FielData {
  llave_privada?: File;
  certificado?: File;
}
