// Generated by Copilot
using SatGoCliente.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();

// Registrar HttpClient y servicios
builder.Services.AddHttpClient<IFacturaService, FacturaService>();
builder.Services.AddHttpClient<IOpinionCumplimientoService, OpinionCumplimientoService>();
builder.Services.AddHttpClient<ICsfService, CsfService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseRouting();

app.UseAuthorization();

app.MapStaticAssets();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=ConsultaSat}/{action=Index}/{id?}")
    .WithStaticAssets();


app.Run();
