<?php
// Generated by Copilot

require_once __DIR__ . '/../config/api.php';

/**
 * Servicio para descarga de Constancia de Situación Fiscal (CSF) del SAT usando FIEL
 */
class CsfService
{
    /** Ruta del archivo de log */
    private static string $log_file = __DIR__ . '/../logs/csf_service.log';

    /**
     * Escribe una entrada en el log
     * @param string $level  DEBUG | INFO | ERROR
     * @param string $message
     * @param mixed  $context Datos adicionales (array, string, etc.)
     */
    private static function log(string $level, string $message, mixed $context = null): void
    {
        $dir = dirname(self::$log_file);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $timestamp = date('Y-m-d H:i:s');
        $line = "[$timestamp] [$level] $message";

        if ($context !== null) {
            $line .= ' | ' . (is_string($context) ? $context : json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
        }

        file_put_contents(self::$log_file, $line . PHP_EOL, FILE_APPEND | LOCK_EX);
    }

    /**
     * Descarga la CSF usando FIEL
     *
     * @param array $request Datos de la FIEL (rfc, authorization, contrasena, llave_privada, certificado)
     * @return array Respuesta de la API
     */
    public static function descargarCsfFiel(array $request): array
    {
        try {
            self::log('INFO', 'Iniciando descarga CSF', [
                'rfc'           => $request['rfc'] ?? '',
                'tiene_key'     => !empty($request['llave_privada']['tmp_name']),
                'tiene_cer'     => !empty($request['certificado']['tmp_name']),
                'authorization' => substr($request['authorization'] ?? '', 0, 20) . '...'
            ]);

            $url = ApiConfig::BASE_URL . ApiConfig::ENDPOINTS['CONSULTAR_CSFFIEL'];
            self::log('INFO', 'URL destino', $url);

            $ch = curl_init();

            // Preparar datos multipart
            $post_fields = [
                'Contrasena' => $request['contrasena']
            ];

            if (!empty($request['llave_privada']) && file_exists($request['llave_privada']['tmp_name'])) {
                $post_fields['llavePrivada'] = new CURLFile(
                    $request['llave_privada']['tmp_name'],
                    'application/octet-stream',
                    $request['llave_privada']['name']
                );
                self::log('DEBUG', 'Adjuntando llave privada', [
                    'name' => $request['llave_privada']['name'],
                    'size' => $request['llave_privada']['size']
                ]);
            } else {
                self::log('DEBUG', 'Sin llave privada adjunta');
            }

            if (!empty($request['certificado']) && file_exists($request['certificado']['tmp_name'])) {
                $post_fields['Certificado'] = new CURLFile(
                    $request['certificado']['tmp_name'],
                    'application/x-x509-ca-cert',
                    $request['certificado']['name']
                );
                self::log('DEBUG', 'Adjuntando certificado', [
                    'name' => $request['certificado']['name'],
                    'size' => $request['certificado']['size']
                ]);
            } else {
                self::log('DEBUG', 'Sin certificado adjunto');
            }

            $headers = [
                'RFC: ' . $request['rfc'],
                'Authorization: Bearer ' . $request['authorization'],
                'Accept: */*',
                'User-Agent: PHP-SAT-Client/1.0',
                'Cache-Control: no-cache'
            ];

            curl_setopt_array($ch, [
                CURLOPT_URL            => $url,
                CURLOPT_POST           => true,
                CURLOPT_POSTFIELDS     => $post_fields,
                CURLOPT_HTTPHEADER     => $headers,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT        => ApiConfig::TIMEOUT,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false,
                CURLOPT_HEADER         => true  // Incluir headers en la respuesta
            ]);

            $raw       = curl_exec($ch);
            $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
            $curl_error  = curl_error($ch);

            curl_close($ch);

            self::log('INFO', 'Respuesta recibida', [
                'http_code'    => $http_code,
                'header_size'  => $header_size,
                'body_size'    => strlen($raw) - $header_size,
                'curl_error'   => $curl_error ?: null
            ]);

            if ($curl_error) {
                self::log('ERROR', 'Error cURL', $curl_error);
                return [
                    'success' => false,
                    'error'   => 'Error de conexión: ' . $curl_error,
                    'message' => 'Error al conectar con la API'
                ];
            }

            // Separar headers del cuerpo
            $response_headers = substr($raw, 0, $header_size);
            $body             = substr($raw, $header_size);

            // Extraer Content-Type
            $content_type = 'application/octet-stream';
            if (preg_match('/Content-Type:\s*([^\r\n]+)/i', $response_headers, $m)) {
                $content_type = trim($m[1]);
            }

            // Extraer nombre de archivo del Content-Disposition
            $filename = 'constancia_situacion_fiscal.pdf';
            if (preg_match('/filename=([^;\r\n]+)/i', $response_headers, $m)) {
                $filename = trim(trim($m[1]), '"');
            }

            self::log('INFO', 'Headers de respuesta procesados', [
                'content_type' => $content_type,
                'filename'     => $filename,
                'http_code'    => $http_code
            ]);

            if ($http_code >= 200 && $http_code < 300) {
                // Si es PDF, devolver en base64
                if (str_contains($content_type, 'application/pdf')) {
                    self::log('INFO', 'PDF recibido correctamente', [
                        'filename'    => $filename,
                        'pdf_bytes'   => strlen($body)
                    ]);
                    return [
                        'success'      => true,
                        'is_pdf'       => true,
                        'pdf_base64'   => base64_encode($body),
                        'filename'     => $filename,
                        'content_type' => $content_type,
                        'message'      => 'CSF descargada exitosamente'
                    ];
                }

                // Respuesta JSON u otro formato
                self::log('INFO', 'Respuesta no-PDF recibida', ['content_type' => $content_type]);
                return [
                    'success' => true,
                    'data'    => json_decode($body, true) ?? $body,
                    'message' => 'CSF descargada exitosamente'
                ];
            } else {
                $data = json_decode($body, true);
                // Si no es JSON válido, usar el texto plano del body como mensaje de error
                $error_message = $data['message'] ?? (trim($body) !== '' ? trim($body) : 'Error HTTP ' . $http_code);
                self::log('ERROR', 'Error HTTP de la API', [
                    'http_code' => $http_code,
                    'body'      => substr($body, 0, 500)
                ]);
                return [
                    'success' => false,
                    'error'   => $error_message,
                    'message' => 'Error al descargar la CSF',
                    'data'    => $data
                ];
            }

        } catch (Exception $e) {
            self::log('ERROR', 'Excepción no controlada', [
                'message' => $e->getMessage(),
                'file'    => $e->getFile(),
                'line'    => $e->getLine()
            ]);
            return [
                'success' => false,
                'error'   => $e->getMessage(),
                'message' => 'Error inesperado al descargar la CSF'
            ];
        }
    }
}
