<?php
// Generated by Copilot

require_once __DIR__ . '/../config/api.php';

/**
 * Servicio para consulta de facturas del SAT usando FIEL
 */
class FacturaService
{
    /**
     * Convierte fecha del formato ISO al formato requerido por la API
     * 
     * @param string $fecha_iso Fecha en formato ISO (2025-10-02T01:30:59)
     * @return string Fecha formateada (2025-10-02 01:30:59)
     */
    private static function formatFechaParaAPI(string $fecha_iso): string
    {
        // Convertir de 2025-10-02T01:30:59 a 2025-10-02 01:30:59
        $fecha_con_espacio = str_replace('T', ' ', $fecha_iso);
        
        // Si no tiene segundos, agregarlos
        if (strlen($fecha_con_espacio) === 16) { // yyyy-mm-dd hh:mm
            return $fecha_con_espacio . ':00';
        }
        
        return $fecha_con_espacio;
    }

    /**
     * Consulta facturas usando FIEL
     * 
     * @param array $params Parámetros de consulta
     * @param array $request Datos de la FIEL
     * @return array Respuesta de la API
     */
    public static function consultarFacturaFiel(array $params, array $request): array
    {
        try {
            // Construir query parameters
            $query_params = http_build_query([
                'tipoBusqueda' => $params['tipo_busqueda'],
                'estatusFactura' => $params['estatus_factura'],
                'fecha_inicial' => self::formatFechaParaAPI($params['fecha_inicial']),
                'tipo' => $params['tipo'],
                'descargaComprobantes' => $params['descarga_comprobantes'] ? 'TRUE' : 'FALSE',
                'fecha_final' => self::formatFechaParaAPI($params['fecha_final'])
            ]);

            // Agregar requestId si existe para reusar sesión
            if (!empty($request['request_id'])) {
                $query_params .= '&requestId=' . urlencode($request['request_id']);
            }

            // URL completa
            $url = ApiConfig::BASE_URL . ApiConfig::ENDPOINTS['CONSULTAR_FACFIEL'] . '?' . $query_params;

            // Inicializar cURL
            $ch = curl_init();

            // Preparar datos multipart
            $post_fields = [
                'Contrasena' => $request['contrasena']
            ];

            // Agregar archivos si existen
            if (!empty($request['llave_privada']) && file_exists($request['llave_privada']['tmp_name'])) {
                $post_fields['llavePrivada'] = new CURLFile(
                    $request['llave_privada']['tmp_name'],
                    'application/octet-stream',
                    $request['llave_privada']['name']
                );
            }

            if (!empty($request['certificado']) && file_exists($request['certificado']['tmp_name'])) {
                $post_fields['Certificado'] = new CURLFile(
                    $request['certificado']['tmp_name'],
                    'application/x-x509-ca-cert',
                    $request['certificado']['name']
                );
            }

            // Configurar headers
            $headers = [
                'RFC: ' . $request['rfc'],
                'Authorization: Bearer ' . $request['authorization'],
                'Accept: */*',
                'User-Agent: PHP-SAT-Client/1.0',
                'Cache-Control: no-cache'
            ];

            // Configurar opciones de cURL
            curl_setopt_array($ch, [
                CURLOPT_URL => $url,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => $post_fields,
                CURLOPT_HTTPHEADER => $headers,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT => ApiConfig::TIMEOUT,
                CURLOPT_SSL_VERIFYPEER => false, // Para desarrollo con certificados auto-firmados
                CURLOPT_SSL_VERIFYHOST => false
            ]);

            // Ejecutar la petición
            $response = curl_exec($ch);
            $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $curl_error = curl_error($ch);
            
            curl_close($ch);

            // Verificar errores de cURL
            if ($curl_error) {
                return [
                    'success' => false,
                    'error' => 'Error de conexión: ' . $curl_error,
                    'message' => 'Error al conectar con la API'
                ];
            }

            // Decodificar respuesta JSON
            $data = json_decode($response, true);

            // Verificar código HTTP
            if ($http_code >= 200 && $http_code < 300) {
                return [
                    'success' => true,
                    'data' => $data,
                    'message' => 'Consulta realizada exitosamente'
                ];
            } else {
                return [
                    'success' => false,
                    'error' => $data['message'] ?? 'Error HTTP ' . $http_code,
                    'message' => 'Error al consultar facturas',
                    'data' => $data
                ];
            }

        } catch (Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage(),
                'message' => 'Error inesperado al consultar facturas'
            ];
        }
    }
}
