<?php
// Generated by Copilot

require_once __DIR__ . '/../config/api.php';

/**
 * Servicio para descarga de Opinión de Cumplimiento IMSS (imssoc) del SAT usando CIEC
 */
class ImssocService
{
    /** Ruta del archivo de log */
    private static string $log_file = __DIR__ . '/../logs/imssoc_service.log';

    /**
     * Escribe una entrada en el log
     * @param string $level  DEBUG | INFO | ERROR
     * @param string $message
     * @param mixed  $context Datos adicionales (array, string, etc.)
     */
    private static function log(string $level, string $message, mixed $context = null): void
    {
        $dir = dirname(self::$log_file);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $timestamp = date('Y-m-d H:i:s');
        $line = "[$timestamp] [$level] $message";

        if ($context !== null) {
            $line .= ' | ' . (is_string($context) ? $context : json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
        }

        file_put_contents(self::$log_file, $line . PHP_EOL, FILE_APPEND | LOCK_EX);
    }

    /**
     * Descarga la Opinión de Cumplimiento IMSS usando CIEC.
     * GET /api/v2/Consultar/imssoc con headers RFC, Authorization y Secret.
     *
     * @param array $request ['rfc', 'authorization', 'ciec']
     * @return array Respuesta de la API
     */
    public static function descargarImssocCiec(array $request): array
    {
        try {
            self::log('INFO', 'Iniciando descarga IMSSOC (CIEC)', [
                'rfc'           => $request['rfc'] ?? '',
                'authorization' => substr($request['authorization'] ?? '', 0, 20) . '...'
            ]);

            $url = ApiConfig::BASE_URL . ApiConfig::ENDPOINTS['CONSULTAR_IMSSOC'];
            self::log('INFO', 'URL destino', $url);

            $ch = curl_init();
            curl_setopt_array($ch, [
                CURLOPT_URL            => $url,
                CURLOPT_HTTPGET        => true,
                CURLOPT_HTTPHEADER     => [
                    'RFC: '                  . $request['rfc'],
                    'Authorization: Bearer ' . $request['authorization'],
                    'Secret: '               . $request['ciec'],
                    'Accept: */*',
                    'User-Agent: PHP-SAT-Client/1.0',
                    'Cache-Control: no-cache'
                ],
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT        => ApiConfig::TIMEOUT,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false,
                CURLOPT_HEADER         => true
            ]);

            $raw         = curl_exec($ch);
            $http_code   = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
            $curl_error  = curl_error($ch);
            curl_close($ch);

            self::log('INFO', 'Respuesta recibida (CIEC)', [
                'http_code'  => $http_code,
                'body_size'  => strlen($raw) - $header_size,
                'curl_error' => $curl_error ?: null
            ]);

            if ($curl_error) {
                self::log('ERROR', 'Error cURL', $curl_error);
                return ['success' => false, 'error' => 'Error de conexión: ' . $curl_error, 'message' => 'Error al conectar con la API'];
            }

            $response_headers = substr($raw, 0, $header_size);
            $body             = substr($raw, $header_size);

            $content_type = 'application/octet-stream';
            if (preg_match('/Content-Type:\s*([^\r\n]+)/i', $response_headers, $m)) {
                $content_type = trim($m[1]);
            }

            $filename = 'opinion_cumplimiento_imss.pdf';
            if (preg_match('/filename=([^;\r\n]+)/i', $response_headers, $m)) {
                $filename = trim(trim($m[1]), '"');
            }

            self::log('INFO', 'Headers de respuesta procesados', [
                'content_type' => $content_type,
                'filename'     => $filename,
                'http_code'    => $http_code
            ]);

            if ($http_code >= 200 && $http_code < 300) {
                if (str_contains($content_type, 'application/pdf')) {
                    self::log('INFO', 'PDF IMSSOC recibido', ['filename' => $filename, 'bytes' => strlen($body)]);
                    return [
                        'success'      => true,
                        'is_pdf'       => true,
                        'pdf_base64'   => base64_encode($body),
                        'filename'     => $filename,
                        'content_type' => $content_type,
                        'message'      => 'Opinión de Cumplimiento IMSS descargada exitosamente'
                    ];
                }

                self::log('INFO', 'Respuesta no-PDF recibida', ['content_type' => $content_type]);
                return [
                    'success' => true,
                    'data'    => json_decode($body, true) ?? $body,
                    'message' => 'Opinión de Cumplimiento IMSS descargada exitosamente'
                ];
            }

            $data          = json_decode($body, true);
            $error_message = $data['message'] ?? (trim($body) !== '' ? trim($body) : 'Error HTTP ' . $http_code);
            self::log('ERROR', 'Error HTTP (CIEC)', ['http_code' => $http_code, 'body' => substr($body, 0, 500)]);
            return [
                'success' => false,
                'error'   => $error_message,
                'message' => 'Error al descargar la Opinión de Cumplimiento IMSS',
                'data'    => $data
            ];

        } catch (Exception $e) {
            self::log('ERROR', 'Excepción no controlada', ['message' => $e->getMessage()]);
            return ['success' => false, 'error' => $e->getMessage(), 'message' => 'Error inesperado al descargar la Opinión de Cumplimiento IMSS'];
        }
    }
}
