<?php
// Generated by Copilot

require_once __DIR__ . '/../config/api.php';

/**
 * Servicio para consulta de Información Fiscal del SAT usando FIEL o CIEC
 */
class InfoFiscalService
{
    /** Ruta del archivo de log */
    private static string $log_file = __DIR__ . '/../logs/info_fiscal_service.log';

    /**
     * Escribe una entrada en el log
     * @param string $level  DEBUG | INFO | ERROR
     * @param string $message
     * @param mixed  $context Datos adicionales (array, string, etc.)
     */
    private static function log(string $level, string $message, mixed $context = null): void
    {
        $dir = dirname(self::$log_file);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $timestamp = date('Y-m-d H:i:s');
        $line = "[$timestamp] [$level] $message";

        if ($context !== null) {
            $line .= ' | ' . (is_string($context) ? $context : json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
        }

        file_put_contents(self::$log_file, $line . PHP_EOL, FILE_APPEND | LOCK_EX);
    }

    /**
     * Consulta Información Fiscal usando FIEL.
     * POST /api/v2/Consultar/informacionfiscalfiel con multipart/form-data.
     *
     * @param array $params  ['request_id']
     * @param array $request ['rfc', 'authorization', 'contrasena', 'llave_privada', 'certificado']
     * @return array Respuesta de la API
     */
    public static function consultarInfoFiscalFiel(array $params, array $request): array
    {
        try {
            self::log('INFO', 'Iniciando consulta Información Fiscal (FIEL)', [
                'rfc'           => $request['rfc'] ?? '',
                'request_id'    => $params['request_id'] ?? null,
                'tiene_key'     => !empty($request['llave_privada']['tmp_name']),
                'tiene_cer'     => !empty($request['certificado']['tmp_name']),
                'authorization' => substr($request['authorization'] ?? '', 0, 20) . '...'
            ]);

            $query = '';
            if (!empty($params['request_id'])) {
                $query = '?' . http_build_query(['requestId' => $params['request_id']]);
            }

            $url = ApiConfig::BASE_URL . ApiConfig::ENDPOINTS['CONSULTAR_INFOFISCALFIEL'] . $query;
            self::log('INFO', 'URL destino (FIEL)', $url);

            $ch = curl_init();

            $post_fields = ['Contrasena' => $request['contrasena']];

            if (!empty($request['llave_privada']) && file_exists($request['llave_privada']['tmp_name'])) {
                $post_fields['llavePrivada'] = new CURLFile(
                    $request['llave_privada']['tmp_name'],
                    'application/octet-stream',
                    $request['llave_privada']['name']
                );
                self::log('DEBUG', 'Adjuntando llave privada', [
                    'name' => $request['llave_privada']['name'],
                    'size' => $request['llave_privada']['size']
                ]);
            } else {
                self::log('DEBUG', 'Sin llave privada adjunta');
            }

            if (!empty($request['certificado']) && file_exists($request['certificado']['tmp_name'])) {
                $post_fields['Certificado'] = new CURLFile(
                    $request['certificado']['tmp_name'],
                    'application/x-x509-ca-cert',
                    $request['certificado']['name']
                );
                self::log('DEBUG', 'Adjuntando certificado', [
                    'name' => $request['certificado']['name'],
                    'size' => $request['certificado']['size']
                ]);
            } else {
                self::log('DEBUG', 'Sin certificado adjunto');
            }

            $headers = [
                'RFC: '                  . $request['rfc'],
                'Authorization: Bearer ' . $request['authorization'],
                'Accept: */*',
                'User-Agent: PHP-SAT-Client/1.0',
                'Cache-Control: no-cache'
            ];

            curl_setopt_array($ch, [
                CURLOPT_URL            => $url,
                CURLOPT_POST           => true,
                CURLOPT_POSTFIELDS     => $post_fields,
                CURLOPT_HTTPHEADER     => $headers,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT        => ApiConfig::TIMEOUT,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false
            ]);

            $response   = curl_exec($ch);
            $http_code  = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $curl_error = curl_error($ch);
            curl_close($ch);

            self::log('INFO', 'Respuesta recibida (FIEL)', [
                'http_code'  => $http_code,
                'body_size'  => strlen($response),
                'curl_error' => $curl_error ?: null
            ]);

            if ($curl_error) {
                self::log('ERROR', 'Error cURL (FIEL)', $curl_error);
                return ['success' => false, 'error' => 'Error de conexión: ' . $curl_error, 'message' => 'Error al conectar con la API'];
            }

            $data = json_decode($response, true);

            if ($http_code >= 200 && $http_code < 300) {
                self::log('INFO', 'Consulta Información Fiscal (FIEL) exitosa');
                return ['success' => true, 'data' => $data, 'message' => 'Información Fiscal obtenida exitosamente'];
            }

            self::log('ERROR', 'Error HTTP (FIEL)', [
                'http_code' => $http_code,
                'body'      => substr($response, 0, 500)
            ]);
            return [
                'success' => false,
                'error'   => $data['message'] ?? 'Error HTTP ' . $http_code,
                'message' => 'Error al obtener la Información Fiscal',
                'data'    => $data
            ];

        } catch (Exception $e) {
            self::log('ERROR', 'Excepción no controlada (FIEL)', [
                'message' => $e->getMessage(),
                'file'    => $e->getFile(),
                'line'    => $e->getLine()
            ]);
            return ['success' => false, 'error' => $e->getMessage(), 'message' => 'Error inesperado al obtener la Información Fiscal'];
        }
    }

    /**
     * Consulta Información Fiscal usando CIEC.
     * GET /api/v2/Consultar/informacionfiscal con header Secret.
     *
     * @param array $params  ['request_id']
     * @param array $request ['rfc', 'authorization', 'ciec']
     * @return array Respuesta de la API
     */
    public static function consultarInfoFiscalCiec(array $params, array $request): array
    {
        try {
            self::log('INFO', 'Iniciando consulta Información Fiscal (CIEC)', [
                'rfc'           => $request['rfc'] ?? '',
                'request_id'    => $params['request_id'] ?? null,
                'authorization' => substr($request['authorization'] ?? '', 0, 20) . '...'
            ]);

            $query = array_filter([
                'requestId' => $params['request_id'] ?: null
            ], fn($v) => $v !== null && $v !== '');

            $url = ApiConfig::BASE_URL . ApiConfig::ENDPOINTS['CONSULTAR_INFOFISCAL'];
            if (!empty($query)) {
                $url .= '?' . http_build_query($query);
            }
            self::log('INFO', 'URL destino (CIEC)', $url);

            $ch = curl_init();
            curl_setopt_array($ch, [
                CURLOPT_URL            => $url,
                CURLOPT_HTTPGET        => true,
                CURLOPT_HTTPHEADER     => [
                    'RFC: '                  . $request['rfc'],
                    'Authorization: Bearer ' . $request['authorization'],
                    'Secret: '               . $request['ciec'],
                    'Accept: */*',
                    'User-Agent: PHP-SAT-Client/1.0',
                    'Cache-Control: no-cache'
                ],
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT        => ApiConfig::TIMEOUT,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false
            ]);

            $response   = curl_exec($ch);
            $http_code  = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $curl_error = curl_error($ch);
            curl_close($ch);

            self::log('INFO', 'Respuesta recibida (CIEC)', [
                'http_code'  => $http_code,
                'body_size'  => strlen($response),
                'curl_error' => $curl_error ?: null
            ]);

            if ($curl_error) {
                self::log('ERROR', 'Error cURL (CIEC)', $curl_error);
                return ['success' => false, 'error' => 'Error de conexión: ' . $curl_error, 'message' => 'Error al conectar con la API'];
            }

            $data = json_decode($response, true);

            if ($http_code >= 200 && $http_code < 300) {
                self::log('INFO', 'Consulta Información Fiscal (CIEC) exitosa');
                return ['success' => true, 'data' => $data, 'message' => 'Información Fiscal obtenida exitosamente'];
            }

            self::log('ERROR', 'Error HTTP (CIEC)', [
                'http_code' => $http_code,
                'body'      => substr($response, 0, 500)
            ]);
            return [
                'success' => false,
                'error'   => $data['message'] ?? 'Error HTTP ' . $http_code,
                'message' => 'Error al obtener la Información Fiscal',
                'data'    => $data
            ];

        } catch (Exception $e) {
            self::log('ERROR', 'Excepción no controlada (CIEC)', [
                'message' => $e->getMessage(),
                'file'    => $e->getFile(),
                'line'    => $e->getLine()
            ]);
            return ['success' => false, 'error' => $e->getMessage(), 'message' => 'Error inesperado al obtener la Información Fiscal'];
        }
    }
}
