<?php
// Generated by Copilot

header('Content-Type: application/json');

require_once __DIR__ . '/../services/InfoFiscalService.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Método no permitido', 'message' => 'Solo se permiten peticiones POST']);
    exit;
}

try {
    $metodo        = $_POST['if_metodo']        ?? 'fiel';
    $rfc           = $_POST['if_rfc']           ?? '';
    $authorization = $_POST['if_authorization'] ?? '';

    $params = [
        'request_id' => $_POST['if_request_id'] ?? ''
    ];

    if (empty($rfc)) {
        throw new Exception('El RFC es requerido');
    }
    if (empty($authorization)) {
        throw new Exception('El token de autorización es requerido');
    }

    if ($metodo === 'ciec') {
        $ciec = $_POST['if_ciec'] ?? '';
        if (empty($ciec)) {
            throw new Exception('La CIEC es requerida');
        }
        $resultado = InfoFiscalService::consultarInfoFiscalCiec($params, [
            'rfc'           => $rfc,
            'authorization' => $authorization,
            'ciec'          => $ciec
        ]);

    } else {
        $contrasena = $_POST['if_contrasena'] ?? '';
        if (empty($contrasena)) {
            throw new Exception('La contraseña de la FIEL es requerida');
        }
        $resultado = InfoFiscalService::consultarInfoFiscalFiel($params, [
            'rfc'           => $rfc,
            'authorization' => $authorization,
            'contrasena'    => $contrasena,
            'llave_privada' => $_FILES['if_llave_privada'] ?? null,
            'certificado'   => $_FILES['if_certificado']   ?? null
        ]);
    }

    echo json_encode($resultado);

} catch (Exception $e) {
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => $e->getMessage(), 'message' => 'Error de validación']);
}
