<?php
// Generated by Copilot

header('Content-Type: application/json');

require_once __DIR__ . '/../services/DecService.php';

// Verificar que sea una petición POST
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode([
        'success' => false,
        'error'   => 'Método no permitido',
        'message' => 'Solo se permiten peticiones POST'
    ]);
    exit;
}

try {
    // Parámetros de la declaración
    $params = [
        'ejercicio'      => $_POST['dec_ejercicio']      ?? '',
        'mes'            => $_POST['dec_mes']            ?? '',
        'tipo_documento' => $_POST['dec_tipo_documento'] ?? '',
        'request_id'     => $_POST['dec_request_id']     ?? ''
    ];

    // Datos FIEL
    $request = [
        'rfc'           => $_POST['dec_rfc']           ?? '',
        'authorization' => $_POST['dec_authorization'] ?? '',
        'contrasena'    => $_POST['dec_contrasena']    ?? '',
        'llave_privada' => $_FILES['dec_llave_privada'] ?? null,
        'certificado'   => $_FILES['dec_certificado']   ?? null
    ];

    // Validar campos requeridos
    if (empty($request['rfc'])) {
        throw new Exception('El RFC es requerido');
    }
    if (empty($request['authorization'])) {
        throw new Exception('El token de autorización es requerido');
    }
    if (empty($request['contrasena'])) {
        throw new Exception('La contraseña es requerida');
    }
    if (empty($params['ejercicio'])) {
        throw new Exception('El ejercicio es requerido');
    }
    if (empty($params['mes'])) {
        throw new Exception('El mes es requerido');
    }
    if (empty($params['tipo_documento'])) {
        throw new Exception('El tipo de documento es requerido');
    }

    $resultado = DecService::descargarDecFiel($params, $request);

    echo json_encode($resultado);

} catch (Exception $e) {
    http_response_code(400);
    echo json_encode([
        'success' => false,
        'error'   => $e->getMessage(),
        'message' => 'Error de validación'
    ]);
}
