<?php
// Generated by Copilot

header('Content-Type: application/json');

require_once __DIR__ . '/../services/CsfService.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode([
        'success' => false,
        'error'   => 'Método no permitido',
        'message' => 'Solo se permiten peticiones POST'
    ]);
    exit;
}

try {
    $metodo        = $_POST['csf_metodo']        ?? 'fiel';
    $rfc           = $_POST['csf_rfc']           ?? '';
    $authorization = $_POST['csf_authorization'] ?? '';

    if (empty($rfc)) {
        throw new Exception('El RFC es requerido');
    }
    if (empty($authorization)) {
        throw new Exception('El token de autorización es requerido');
    }

    if ($metodo === 'ciec') {
        $ciec = $_POST['csf_ciec'] ?? '';
        if (empty($ciec)) {
            throw new Exception('La CIEC es requerida');
        }

        $resultado = CsfService::descargarCsfCiec([
            'rfc'           => $rfc,
            'authorization' => $authorization,
            'ciec'          => $ciec
        ]);

    } else {
        $contrasena = $_POST['csf_contrasena'] ?? '';
        if (empty($contrasena)) {
            throw new Exception('La contraseña de la FIEL es requerida');
        }

        $resultado = CsfService::descargarCsfFiel([
            'rfc'           => $rfc,
            'authorization' => $authorization,
            'contrasena'    => $contrasena,
            'llave_privada' => $_FILES['csf_llave_privada'] ?? null,
            'certificado'   => $_FILES['csf_certificado']   ?? null
        ]);
    }

    echo json_encode($resultado);

} catch (Exception $e) {
    http_response_code(400);
    echo json_encode([
        'success' => false,
        'error'   => $e->getMessage(),
        'message' => 'Error de validación'
    ]);
}
