<?php
// Generated by Copilot

header('Content-Type: application/json');

require_once __DIR__ . '/../services/CsfService.php';

// Verificar que sea una petición POST
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode([
        'success' => false,
        'error'   => 'Método no permitido',
        'message' => 'Solo se permiten peticiones POST'
    ]);
    exit;
}

try {
    // Obtener datos FIEL
    $request = [
        'rfc'           => $_POST['csf_rfc']           ?? '',
        'authorization' => $_POST['csf_authorization'] ?? '',
        'contrasena'    => $_POST['csf_contrasena']    ?? '',
        'llave_privada' => $_FILES['csf_llave_privada'] ?? null,
        'certificado'   => $_FILES['csf_certificado']   ?? null
    ];

    // Validar campos requeridos
    if (empty($request['rfc'])) {
        throw new Exception('El RFC es requerido');
    }
    if (empty($request['authorization'])) {
        throw new Exception('El token de autorización es requerido');
    }
    if (empty($request['contrasena'])) {
        throw new Exception('La contraseña es requerida');
    }

    $resultado = CsfService::descargarCsfFiel($request);

    echo json_encode($resultado);

} catch (Exception $e) {
    http_response_code(400);
    echo json_encode([
        'success' => false,
        'error'   => $e->getMessage(),
        'message' => 'Error de validación'
    ]);
}
