<?php
// Generated by Copilot

header('Content-Type: application/json');

require_once __DIR__ . '/../services/ImssocService.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Método no permitido', 'message' => 'Solo se permiten peticiones POST']);
    exit;
}

try {
    $rfc           = $_POST['imssoc_rfc']           ?? '';
    $authorization = $_POST['imssoc_authorization'] ?? '';
    $ciec          = $_POST['imssoc_ciec']          ?? '';

    if (empty($rfc)) {
        throw new Exception('El RFC es requerido');
    }
    if (empty($authorization)) {
        throw new Exception('El token de autorización es requerido');
    }
    if (empty($ciec)) {
        throw new Exception('La CIEC es requerida');
    }

    $resultado = ImssocService::descargarImssocCiec([
        'rfc'           => $rfc,
        'authorization' => $authorization,
        'ciec'          => $ciec
    ]);

    echo json_encode($resultado);

} catch (Exception $e) {
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => $e->getMessage(), 'message' => 'Error de validación']);
}
