// Generated by Copilot
import React, { useState } from 'react';
import { 
  Form, 
  Button, 
  Row, 
  Col, 
  Card, 
  Alert, 
  Spinner,
  FormControl,
  FormGroup,
  FormLabel,
  FormSelect,
  Modal
} from 'react-bootstrap';
import type { ConsultaFacturaParams, FacturaFielRequest } from '../types/FacturaTypes';
import { consultarFacturaFiel } from '../services/FacturaService';
import { FORM_DEFAULTS } from '../config/api';

interface ConsultaFacturaFormProps {
  onResult?: (result: any) => void;
}

const ConsultaFacturaForm: React.FC<ConsultaFacturaFormProps> = ({ onResult }) => {
  const [loading, setLoading] = useState(false);
  const [alert, setAlert] = useState<{ type: 'success' | 'danger'; message: string } | null>(null);
  const [showErrorModal, setShowErrorModal] = useState(false);
  const [errorDetails, setErrorDetails] = useState<{ title: string; message: string; details?: any }>({ title: '', message: '' });

  // Función para mostrar el formato que se enviará a la API
  const formatFechaParaVista = (fechaISO: string): string => {
    const fechaConEspacio = fechaISO.replace('T', ' ');
    return fechaConEspacio.length === 16 ? fechaConEspacio + ':00' : fechaConEspacio;
  };
  
  // Estados del formulario
  const [formData, setFormData] = useState<ConsultaFacturaParams>({
    tipo_busqueda: FORM_DEFAULTS.TIPO_BUSQUEDA,
    estatus_factura: FORM_DEFAULTS.ESTATUS_FACTURA,
    fecha_inicial: FORM_DEFAULTS.FECHA_INICIAL,
    tipo: FORM_DEFAULTS.TIPO,
    descarga_comprobantes: FORM_DEFAULTS.DESCARGA_COMPROBANTES,
    fecha_final: FORM_DEFAULTS.FECHA_FINAL
  });

  const [fielData, setFielData] = useState<FacturaFielRequest>({
    rfc: FORM_DEFAULTS.RFC,
    authorization: '',
    contrasena: FORM_DEFAULTS.CONTRASENA
  });

  const [requestId, setRequestId] = useState<string>('');

  const [files, setFiles] = useState<{
    llave_privada?: File;
    certificado?: File;
  }>({});

  const handleFormChange = (field: keyof ConsultaFacturaParams, value: any) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleFielChange = (field: keyof FacturaFielRequest, value: any) => {
    setFielData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleFileChange = (field: 'llave_privada' | 'certificado', file: File | null) => {
    if (file) {
      setFiles(prev => ({
        ...prev,
        [field]: file
      }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setAlert(null);

    try {
      const request: FacturaFielRequest = {
        ...fielData,
        llave_privada: files.llave_privada,
        certificado: files.certificado,
        request_id: requestId.trim() !== '' ? requestId : undefined
      };

      const result = await consultarFacturaFiel(formData, request);
      
      if (result.success) {
        setAlert({ type: 'success', message: result.message || 'Consulta exitosa' });
        if (onResult) {
          onResult(result.data);
        }
        // Si hay requestId en la respuesta, guardarlo para reusar sesión
        if (result.data?.requestId) {
          setRequestId(result.data.requestId);
        }
      } else {
        // Mostrar error en modal
        setErrorDetails({
          title: 'Error en la consulta',
          message: result.error || 'Error desconocido en la consulta',
          details: result
        });
        setShowErrorModal(true);
      }
    } catch (error: any) {
      setErrorDetails({
        title: 'Error inesperado',
        message: 'Error inesperado al realizar la consulta',
        details: error
      });
      setShowErrorModal(true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card>
      <Card.Header>
        <Card.Title className="mb-0">Consulta de Facturas FIEL</Card.Title>
      </Card.Header>
      <Card.Body>
        {alert && (
          <Alert variant={alert.type} dismissible onClose={() => setAlert(null)}>
            {alert.message}
          </Alert>
        )}

        <Form onSubmit={handleSubmit}>
          {/* Datos FIEL */}
          <Row className="mb-3">
            <Col>
              <h5>Información FIEL</h5>
            </Col>
          </Row>

          <Row className="mb-3">
            <Col md={6}>
              <FormGroup>
                <FormLabel>RFC</FormLabel>
                <FormControl
                  type="text"
                  value={fielData.rfc}
                  onChange={(e) => handleFielChange('rfc', e.target.value)}
                  placeholder="RFC del contribuyente"
                  required
                />
              </FormGroup>
            </Col>
            <Col md={6}>
              <FormGroup>
                <FormLabel>Contraseña</FormLabel>
                <FormControl
                  type="password"
                  value={fielData.contrasena}
                  onChange={(e) => handleFielChange('contrasena', e.target.value)}
                  placeholder="Contraseña de la FIEL"
                  required
                />
              </FormGroup>
            </Col>
          </Row>

          <Row className="mb-3">
            <Col md={12}>
              <FormGroup>
                <FormLabel>Token de Autorización</FormLabel>
                <FormControl
                  as="textarea"
                  rows={3}
                  value={fielData.authorization}
                  onChange={(e) => handleFielChange('authorization', e.target.value)}
                  placeholder="Bearer token de autorización"
                  required
                />
              </FormGroup>
            </Col>
          </Row>

          <Row className="mb-3">
            <Col md={12}>
              <FormGroup>
                <FormLabel>Request ID (Opcional - para reusar sesión)</FormLabel>
                <FormControl
                  type="text"
                  value={requestId}
                  onChange={(e) => setRequestId(e.target.value)}
                  placeholder="ID de request para mantener la sesión activa"
                />
                <Form.Text className="text-muted">
                  Si tienes un Request ID de una consulta anterior, ingrésalo aquí para reusar la sesión.
                </Form.Text>
              </FormGroup>
            </Col>
          </Row>

          <Row className="mb-3">
            <Col md={6}>
              <FormGroup>
                <FormLabel>Llave Privada (.key)</FormLabel>
                <FormControl
                  type="file"
                  accept=".key"
                  onChange={(e) => {
                    const file = (e.target as HTMLInputElement).files?.[0];
                    handleFileChange('llave_privada', file || null);
                  }}
                />
              </FormGroup>
            </Col>
            <Col md={6}>
              <FormGroup>
                <FormLabel>Certificado (.cer)</FormLabel>
                <FormControl
                  type="file"
                  accept=".cer"
                  onChange={(e) => {
                    const file = (e.target as HTMLInputElement).files?.[0];
                    handleFileChange('certificado', file || null);
                  }}
                />
              </FormGroup>
            </Col>
          </Row>

          {/* Parámetros de consulta */}
          <Row className="mb-3">
            <Col>
              <h5>Parámetros de Consulta</h5>
            </Col>
          </Row>

          <Row className="mb-3">
            <Col md={4}>
              <FormGroup>
                <FormLabel>Tipo de Búsqueda</FormLabel>
                <FormSelect
                  value={formData.tipo_busqueda}
                  onChange={(e) => handleFormChange('tipo_busqueda', parseInt(e.target.value))}
                >
                  <option value={1}>Por Fecha</option>
                  <option value={2}>Por Folio</option>
                </FormSelect>
              </FormGroup>
            </Col>
            <Col md={4}>
              <FormGroup>
                <FormLabel>Estatus Factura</FormLabel>
                <FormSelect
                  value={formData.estatus_factura}
                  onChange={(e) => handleFormChange('estatus_factura', parseInt(e.target.value))}
                >
                  <option value={-1}>Todos</option>
                  <option value={1}>Vigente</option>
                  <option value={0}>Cancelada</option>
                </FormSelect>
              </FormGroup>
            </Col>
            <Col md={4}>
              <FormGroup>
                <FormLabel>Tipo</FormLabel>
                <FormSelect
                  value={formData.tipo}
                  onChange={(e) => handleFormChange('tipo', e.target.value as 'recibidos' | 'emitidos')}
                >
                  <option value="recibidos">Recibidos</option>
                  <option value="emitidos">Emitidos</option>
                </FormSelect>
              </FormGroup>
            </Col>
          </Row>

          <Row className="mb-3">
            <Col md={5}>
              <FormGroup>
                <FormLabel>Fecha Inicial</FormLabel>
                <FormControl
                  type="datetime-local"
                  step="1"
                  value={formData.fecha_inicial}
                  onChange={(e) => handleFormChange('fecha_inicial', e.target.value)}
                  required
                />
                <Form.Text className="text-muted">
                  Formato enviado: {formatFechaParaVista(formData.fecha_inicial)}
                </Form.Text>
              </FormGroup>
            </Col>
            <Col md={5}>
              <FormGroup>
                <FormLabel>Fecha Final</FormLabel>
                <FormControl
                  type="datetime-local"
                  step="1"
                  value={formData.fecha_final}
                  onChange={(e) => handleFormChange('fecha_final', e.target.value)}
                  required
                />
                <Form.Text className="text-muted">
                  Formato enviado: {formatFechaParaVista(formData.fecha_final)}
                </Form.Text>
              </FormGroup>
            </Col>
            <Col md={2}>
              <FormGroup>
                <FormLabel>Descargar Comprobantes</FormLabel>
                <Form.Check
                  type="checkbox"
                  checked={formData.descarga_comprobantes}
                  onChange={(e) => handleFormChange('descarga_comprobantes', e.target.checked)}
                  label="Sí"
                />
              </FormGroup>
            </Col>
          </Row>

          <Row>
            <Col className="d-grid">
              <Button
                variant="primary"
                type="submit"
                disabled={loading}
                size="lg"
              >
                {loading ? (
                  <>
                    <Spinner animation="border" size="sm" className="me-2" />
                    Consultando...
                  </>
                ) : (
                  'Consultar Facturas'
                )}
              </Button>
            </Col>
          </Row>
        </Form>
      </Card.Body>

      {/* Generated by Copilot - Modal de Error */}
      <Modal show={showErrorModal} onHide={() => setShowErrorModal(false)} size="lg">
        <Modal.Header closeButton>
          <Modal.Title className="text-danger">{errorDetails.title}</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Alert variant="danger">
            <Alert.Heading>Error</Alert.Heading>
            <p>{errorDetails.message}</p>
            
            {errorDetails.details && (
              <details className="mt-3">
                <summary className="text-muted">Ver detalles técnicos</summary>
                <pre className="mt-2 text-small bg-light p-2 rounded">
                  {JSON.stringify(errorDetails.details, null, 2)}
                </pre>
              </details>
            )}
          </Alert>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setShowErrorModal(false)}>
            Cerrar
          </Button>
          <Button 
            variant="primary" 
            onClick={() => {
              setShowErrorModal(false);
              // Reintentar la consulta automáticamente
              handleSubmit(new Event('submit') as any);
            }}
          >
            Reintentar
          </Button>
        </Modal.Footer>
      </Modal>
    </Card>
  );
};

export default ConsultaFacturaForm;