// Generated by Copilot
import React, { useState } from 'react';
import { 
  Form, 
  Button, 
  Row, 
  Col, 
  Card, 
  Alert, 
  Spinner,
  Modal
} from 'react-bootstrap';
import type { CsfFielRequest } from '../types/CsfTypes';
import type { FielData, FielFiles } from '../types/FielTypes';
import { consultarCsf, downloadCsfPdf } from '../services/CsfService';

interface CsfFormProps {
  onResult?: (result: any) => void;
  fielData: FielData; // Generated by Copilot - Datos FIEL desde App
  files: FielFiles; // Generated by Copilot - Archivos FIEL desde App
}

const CsfForm: React.FC<CsfFormProps> = ({ onResult, fielData, files }) => {
  const [loading, setLoading] = useState(false);
  const [alert, setAlert] = useState<{ type: 'success' | 'danger'; message: string } | null>(null);
  const [showErrorModal, setShowErrorModal] = useState(false);
  const [errorDetails, setErrorDetails] = useState<{ title: string; message: string; details?: any }>({ title: '', message: '' });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setAlert(null);

    try {
      const request: CsfFielRequest = {
        ...fielData,
        llave_privada: files.llave_privada,
        certificado: files.certificado
      };

      const result = await consultarCsf(request);
      
      if (result.success && result.data) {
        setAlert({ type: 'success', message: result.message || 'Descarga exitosa' });
        
        // Descargar el PDF automáticamente
        downloadCsfPdf(result.data, 'ConstanciaSituacionFiscal.pdf');
        
        if (onResult) {
          onResult({ success: true, message: 'PDF descargado correctamente' });
        }
      } else {
        // Mostrar error en modal
        setErrorDetails({
          title: 'Error en la consulta',
          message: result.error || 'Error desconocido en la consulta',
          details: result.error_data || result
        });
        setShowErrorModal(true);
      }
    } catch (error: any) {
      setErrorDetails({
        title: 'Error inesperado',
        message: 'Error inesperado al realizar la consulta',
        details: error
      });
      setShowErrorModal(true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card>
      <Card.Header>
        <Card.Title className="mb-0">Constancia de Situación Fiscal (CSF)</Card.Title>
      </Card.Header>
      <Card.Body>
        {alert && (
          <Alert variant={alert.type} dismissible onClose={() => setAlert(null)}>
            {alert.message}
          </Alert>
        )}

        <Alert variant="info" className="mb-4">
          <Alert.Heading>¿Qué es la Constancia de Situación Fiscal?</Alert.Heading>
          <p className="mb-0">
            La Constancia de Situación Fiscal (CSF) es un documento oficial emitido por el SAT 
            que contiene los datos fiscales del contribuyente como RFC, régimen fiscal, 
            actividades económicas, domicilio fiscal y obligaciones fiscales. 
            Es frecuentemente requerida para trámites bancarios, contrataciones y facturación.
          </p>
        </Alert>

        <Form onSubmit={handleSubmit}>
          <Row>
            <Col className="d-grid">
              <Button
                variant="primary"
                type="submit"
                disabled={loading}
                size="lg"
              >
                {loading ? (
                  <>
                    <Spinner animation="border" size="sm" className="me-2" />
                    Consultando...
                  </>
                ) : (
                  'Descargar Constancia de Situación Fiscal'
                )}
              </Button>
            </Col>
          </Row>
        </Form>
      </Card.Body>

      {/* Generated by Copilot - Modal de Error */}
      <Modal show={showErrorModal} onHide={() => setShowErrorModal(false)} size="lg">
        <Modal.Header closeButton>
          <Modal.Title className="text-danger">{errorDetails.title}</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Alert variant="danger">
            <Alert.Heading>Error</Alert.Heading>
            <p>{errorDetails.message}</p>
            
            {errorDetails.details && (
              <details className="mt-3">
                <summary className="text-muted">Ver detalles técnicos</summary>
                <pre className="mt-2 text-small bg-light p-2 rounded">
                  {JSON.stringify(errorDetails.details, null, 2)}
                </pre>
              </details>
            )}
          </Alert>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setShowErrorModal(false)}>
            Cerrar
          </Button>
          <Button 
            variant="primary" 
            onClick={() => {
              setShowErrorModal(false);
              // Reintentar la consulta automáticamente
              handleSubmit(new Event('submit') as any);
            }}
          >
            Reintentar
          </Button>
        </Modal.Footer>
      </Modal>
    </Card>
  );
};

export default CsfForm;
