// Generated by Copilot
import React, { useState } from 'react';
import { 
  Table, 
  Card, 
  Badge, 
  Button, 
  Row, 
  Col,
  Alert,
  Collapse,
  Pagination,
  Form
} from 'react-bootstrap';

interface FacturaResultadosProps {
  data: any;
}

const FacturaResultados: React.FC<FacturaResultadosProps> = ({ data }) => {
  const [expandedRows, setExpandedRows] = useState<Set<number>>(new Set());
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(5);

  if (!data) {
    return (
      <Alert variant="info">
        No hay resultados para mostrar. Realiza una consulta para ver las facturas.
      </Alert>
    );
  }

  // Manejar error de la API
  if (data.success === false) {
    return (
      <Alert variant="danger">
        <Alert.Heading>Error en la consulta</Alert.Heading>
        <p>{data.errorMessage || 'Error desconocido en la respuesta de la API'}</p>
        {data.requestId && <small>Request ID: {data.requestId}</small>}
      </Alert>
    );
  }

  const toggleRow = (index: number) => {
    const newExpanded = new Set(expandedRows);
    if (newExpanded.has(index)) {
      newExpanded.delete(index);
    } else {
      newExpanded.add(index);
    }
    setExpandedRows(newExpanded);
  };

  // Extraer comprobantes de la respuesta de la API
  const facturas = data.comprobantes || [];

  // Cálculos de paginación
  const totalPages = Math.ceil(facturas.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentFacturas = facturas.slice(startIndex, endIndex);

  // Resetear página cuando cambian los datos
  React.useEffect(() => {
    setCurrentPage(1);
    setExpandedRows(new Set());
  }, [data]);

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
    setExpandedRows(new Set()); // Colapsar filas expandidas al cambiar página
  };

  const handleItemsPerPageChange = (newItemsPerPage: number) => {
    setItemsPerPage(newItemsPerPage);
    setCurrentPage(1); // Resetear a primera página
    setExpandedRows(new Set());
  };

  return (
    <Card className="mt-4">
      <Card.Header>
        <Row className="align-items-center">
          <Col>
            <Card.Title className="mb-0">Resultados de la Consulta</Card.Title>
            {data.success && (
              <small className="text-muted">Request ID: {data.requestId}</small>
            )}
            {totalPages > 1 && (
              <small className="text-muted d-block">Página {currentPage} de {totalPages}</small>
            )}
          </Col>
          <Col xs="auto">
            <Badge bg="primary">{data.count || facturas.length} factura(s) encontrada(s)</Badge>
            {data.success !== undefined && (
              <Badge bg={data.success ? "success" : "danger"} className="ms-2">
                {data.success ? "Éxito" : "Error"}
              </Badge>
            )}
          </Col>
        </Row>
      </Card.Header>
      <Card.Body>
        {facturas.length === 0 ? (
          <Alert variant="warning">
            No se encontraron facturas con los criterios especificados.
          </Alert>
        ) : (
          <Table responsive striped hover>
            <thead>
              <tr>
                <th>Acciones</th>
                <th>RFC Emisor</th>
                <th>Emisor</th>
                <th>RFC Receptor</th>
                <th>Fecha Emisión</th>
                <th>Total</th>
                <th>Estado</th>
                <th>UUID</th>
              </tr>
            </thead>
            <tbody>
              {currentFacturas.map((factura: any, index: number) => (
                <React.Fragment key={startIndex + index}>
                  <tr>
                    <td>
                      <Button
                        variant="outline-primary"
                        size="sm"
                        onClick={() => toggleRow(startIndex + index)}
                      >
                        {expandedRows.has(startIndex + index) ? 'Ocultar' : 'Ver más'}
                      </Button>
                    </td>
                    <td><small>{factura.rfCemisor || 'N/A'}</small></td>
                    <td>{factura.razonSocialEmisor || 'N/A'}</td>
                    <td><small>{factura.rfcReceptor || 'N/A'}</small></td>
                    <td>
                      {factura.fechaEmision ? 
                        new Date(factura.fechaEmision).toLocaleString('es-MX') : 
                        'N/A'
                      }
                    </td>
                    <td>
                      <strong>{factura.total || '$0.00'}</strong>
                    </td>
                    <td>
                      <Badge bg={factura.estadoDeComprobante === 'Vigente' ? 'success' : 'danger'}>
                        {factura.estadoDeComprobante || 'N/A'}
                      </Badge>
                    </td>
                    <td>
                      <small className="text-muted" title={factura.uuid}>
                        {factura.uuid ? 
                          `${factura.uuid.substring(0, 8)}...` : 
                          'N/A'
                        }
                      </small>
                    </td>
                  </tr>
                  <tr>
                    <td colSpan={8} className="p-0">
                      <Collapse in={expandedRows.has(startIndex + index)}>
                        <div className="p-3 bg-light">
                          <Row>
                            <Col md={6}>
                              <h6>Información del Emisor</h6>
                              <p><strong>RFC:</strong> {factura.rfCemisor || 'N/A'}</p>
                              <p><strong>Razón Social:</strong> {factura.razonSocialEmisor || 'N/A'}</p>
                            </Col>
                            <Col md={6}>
                              <h6>Información del Receptor</h6>
                              <p><strong>RFC:</strong> {factura.rfcReceptor || 'N/A'}</p>
                              <p><strong>Razón Social:</strong> {factura.razonSocialReceptor || 'N/A'}</p>
                            </Col>
                          </Row>
                          <Row>
                            <Col md={6}>
                              <h6>Detalles Fiscales</h6>
                              <p><strong>UUID:</strong> <small>{factura.uuid || 'N/A'}</small></p>
                              <p><strong>Efecto:</strong> {factura.efectoDelComprobante || 'N/A'}</p>
                              <p><strong>Estado:</strong> 
                                <Badge bg={factura.estadoDeComprobante === 'Vigente' ? 'success' : 'danger'} className="ms-2">
                                  {factura.estadoDeComprobante || 'N/A'}
                                </Badge>
                              </p>
                              <p><strong>Cancelación:</strong> {factura.estatusCancelacion || 'N/A'}</p>
                            </Col>
                            <Col md={6}>
                              <h6>Fechas y Certificación</h6>
                              <p><strong>Fecha Emisión:</strong> {factura.fechaEmision ? new Date(factura.fechaEmision).toLocaleString('es-MX') : 'N/A'}</p>
                              <p><strong>Fecha Certificación:</strong> {factura.fechaCertificacion ? new Date(factura.fechaCertificacion).toLocaleString('es-MX') : 'N/A'}</p>
                              <p><strong>RFC PAC:</strong> {factura.rfcPac || 'N/A'}</p>
                              <p><strong>Total:</strong> <strong className="text-success">{factura.total || '$0.00'}</strong></p>
                            </Col>
                          </Row>
                          <Row>
                            <Col md={12}>
                              <h6>Descarga</h6>
                              <p><strong>Archivo:</strong> {factura.fileName || 'N/A'}</p>
                              {factura.urlDescarga && (
                                <Button 
                                  variant="outline-primary" 
                                  size="sm"
                                  onClick={() => window.open(factura.urlDescarga, '_blank')}
                                >
                                  Descargar XML
                                </Button>
                              )}
                            </Col>
                          </Row>
                        </div>
                      </Collapse>
                    </td>
                  </tr>
                </React.Fragment>
              ))}
            </tbody>
          </Table>
        )}

        {/* Generated by Copilot - Controles de Paginación */}
        {facturas.length > 0 && (
          <Row className="mt-3">
            <Col md={6}>
              <div className="d-flex align-items-center">
                <span className="me-2">Mostrar:</span>
                <Form.Select
                  size="sm"
                  style={{ width: 'auto' }}
                  value={itemsPerPage}
                  onChange={(e) => handleItemsPerPageChange(parseInt(e.target.value))}
                >
                  <option value={5}>5 por página</option>
                  <option value={10}>10 por página</option>
                  <option value={20}>20 por página</option>
                  <option value={50}>50 por página</option>
                  <option value={facturas.length}>Mostrar todas ({facturas.length})</option>
                </Form.Select>
              </div>
              <small className="text-muted">
                Mostrando {startIndex + 1}-{Math.min(endIndex, facturas.length)} de {facturas.length} facturas
              </small>
            </Col>
            
            {totalPages > 1 && (
              <Col md={6} className="d-flex justify-content-end">
                <Pagination size="sm">
                  <Pagination.First
                    onClick={() => handlePageChange(1)}
                    disabled={currentPage === 1}
                  />
                  <Pagination.Prev
                    onClick={() => handlePageChange(currentPage - 1)}
                    disabled={currentPage === 1}
                  />
                  
                  {/* Páginas numeradas */}
                  {Array.from({ length: Math.min(totalPages, 5) }, (_, i) => {
                    let pageNumber;
                    if (totalPages <= 5) {
                      pageNumber = i + 1;
                    } else if (currentPage <= 3) {
                      pageNumber = i + 1;
                    } else if (currentPage >= totalPages - 2) {
                      pageNumber = totalPages - 4 + i;
                    } else {
                      pageNumber = currentPage - 2 + i;
                    }
                    
                    return (
                      <Pagination.Item
                        key={pageNumber}
                        active={pageNumber === currentPage}
                        onClick={() => handlePageChange(pageNumber)}
                      >
                        {pageNumber}
                      </Pagination.Item>
                    );
                  })}
                  
                  <Pagination.Next
                    onClick={() => handlePageChange(currentPage + 1)}
                    disabled={currentPage === totalPages}
                  />
                  <Pagination.Last
                    onClick={() => handlePageChange(totalPages)}
                    disabled={currentPage === totalPages}
                  />
                </Pagination>
              </Col>
            )}
          </Row>
        )}
      </Card.Body>
    </Card>
  );
};

export default FacturaResultados;