// Generated by Copilot
// Componente compartido para capturar datos FIEL (RFC, contraseña, token, archivos)
import React from 'react';
import { 
  Row, 
  Col, 
  FormControl,
  FormGroup,
  FormLabel,
  Form
} from 'react-bootstrap';
import type { FielData, FielFiles } from '../types/FielTypes';

interface FielDataFormProps {
  fielData: FielData;
  files: FielFiles;
  onFielDataChange: (field: keyof FielData, value: string) => void;
  onFileChange: (field: keyof FielFiles, file: File | null) => void;
  filesRequired?: boolean;
  showRequestId?: boolean;
  requestId?: string;
  onRequestIdChange?: (value: string) => void;
  showToken?: boolean; // Generated by Copilot - Para ocultar el token cuando está a nivel global
}

const FielDataForm: React.FC<FielDataFormProps> = ({
  fielData,
  files,
  onFielDataChange,
  onFileChange,
  filesRequired = false,
  showRequestId = false,
  requestId = '',
  onRequestIdChange,
  showToken = true
}) => {
  return (
    <>
      <Row className="mb-3">
        <Col md={6}>
          <FormGroup>
            <FormLabel>RFC</FormLabel>
            <FormControl
              type="text"
              value={fielData.rfc}
              onChange={(e) => onFielDataChange('rfc', e.target.value)}
              placeholder="RFC del contribuyente"
              required
            />
          </FormGroup>
        </Col>
        <Col md={6}>
          <FormGroup>
            <FormLabel>Contraseña</FormLabel>
            <FormControl
              type="password"
              value={fielData.contrasena}
              onChange={(e) => onFielDataChange('contrasena', e.target.value)}
              placeholder="Contraseña de la FIEL"
              required
            />
          </FormGroup>
        </Col>
      </Row>

      {showToken && (
        <Row className="mb-3">
          <Col md={12}>
            <FormGroup>
              <FormLabel>Token de Autorización</FormLabel>
              <FormControl
                as="textarea"
                rows={3}
                value={fielData.authorization}
                onChange={(e) => onFielDataChange('authorization', e.target.value)}
                placeholder="Bearer token de autorización"
                required
              />
            </FormGroup>
          </Col>
        </Row>
      )}

      {showRequestId && onRequestIdChange && (
        <Row className="mb-3">
          <Col md={12}>
            <FormGroup>
              <FormLabel>Request ID (Opcional - para reusar sesión)</FormLabel>
              <FormControl
                type="text"
                value={requestId}
                onChange={(e) => onRequestIdChange(e.target.value)}
                placeholder="ID de request para mantener la sesión activa"
              />
              <Form.Text className="text-muted">
                Si tienes un Request ID de una consulta anterior, ingrésalo aquí para reusar la sesión.
              </Form.Text>
            </FormGroup>
          </Col>
        </Row>
      )}

      <Row className="mb-3">
        <Col md={6}>
          <FormGroup>
            <FormLabel>Llave Privada (.key)</FormLabel>
            <FormControl
              type="file"
              accept=".key"
              onChange={(e) => {
                const file = (e.target as HTMLInputElement).files?.[0];
                onFileChange('llave_privada', file || null);
              }}
              required={filesRequired}
            />
          </FormGroup>
        </Col>
        <Col md={6}>
          <FormGroup>
            <FormLabel>Certificado (.cer)</FormLabel>
            <FormControl
              type="file"
              accept=".cer"
              onChange={(e) => {
                const file = (e.target as HTMLInputElement).files?.[0];
                onFileChange('certificado', file || null);
              }}
              required={filesRequired}
            />
          </FormGroup>
        </Col>
      </Row>
    </>
  );
};

export default FielDataForm;
