// Generated by Copilot
import React from 'react';
import { Alert, Spinner, Container, Row, Col } from 'react-bootstrap';

interface LoadingSpinnerProps {
  message?: string;
}

export const LoadingSpinner: React.FC<LoadingSpinnerProps> = ({ 
  message = 'Cargando...' 
}) => {
  return (
    <Container className="text-center py-5">
      <Row>
        <Col>
          <Spinner animation="border" variant="primary" className="mb-3" />
          <p className="text-muted">{message}</p>
        </Col>
      </Row>
    </Container>
  );
};

interface ErrorAlertProps {
  error: string;
  onRetry?: () => void;
  onDismiss?: () => void;
}

export const ErrorAlert: React.FC<ErrorAlertProps> = ({ 
  error, 
  onRetry, 
  onDismiss 
}) => {
  return (
    <Alert 
      variant="danger" 
      dismissible={!!onDismiss}
      onClose={onDismiss}
    >
      <Alert.Heading>Error</Alert.Heading>
      <p>{error}</p>
      {onRetry && (
        <div className="d-flex justify-content-end">
          <button 
            className="btn btn-outline-danger"
            onClick={onRetry}
          >
            Intentar de nuevo
          </button>
        </div>
      )}
    </Alert>
  );
};