# Generated by Copilot
import requests
from config.api import BASE_URL_V1, AUTH_ENDPOINTS, TIMEOUT


def _extract_string_value(data) -> str | None:
    """
    Extrae el valor string de la respuesta de la API.
    Maneja: string plano, JSON string, objeto con campos conocidos,
    y estructura anidada tokens.access.value.
    """
    if isinstance(data, str):
        return data

    if isinstance(data, dict):
        # Estructura SAT-GO: tokens.access.value
        try:
            return data['tokens']['access']['value']
        except (KeyError, TypeError):
            pass

        for field in ('key', 'Key', 'apiKey', 'ApiKey',
                      'access_token', 'accessToken', 'token', 'Token',
                      'jwt', 'value', 'data', 'result'):
            if data.get(field) and isinstance(data[field], str):
                return data[field]

    return None


def crear_key(token_portal: str) -> dict:
    """
    Paso 1: Obtiene la API Key permanente usando el token del portal web.

    POST /api/v1/Users/CreateKey
    Header: Authorization: Bearer <token_portal>
    """
    url = BASE_URL_V1 + AUTH_ENDPOINTS['CREATE_KEY']
    headers = {
        'Authorization': f'Bearer {token_portal}',
        'Accept': 'application/json, text/plain, */*',
        'User-Agent': 'Python-SAT-Client/1.0',
        'Cache-Control': 'no-cache',
    }

    try:
        response = requests.post(url, headers=headers, timeout=TIMEOUT, verify=False)
        raw = response.text.strip()

        if response.ok:
            try:
                body = response.json()
            except ValueError:
                body = raw

            key = _extract_string_value(body)
            return {
                'success': True,
                'key': key or raw,
                'message': 'API Key obtenida correctamente',
                'raw_response': raw,
            }

        try:
            err = response.json()
            msg = err.get('message') or err.get('title') or err.get('detail') or f'Error HTTP {response.status_code}'
        except ValueError:
            msg = f'Error HTTP {response.status_code}'

        return {
            'success': False,
            'error': msg,
            'message': 'Error al obtener la API Key',
            'raw_response': raw,
            'http_code': response.status_code,
        }

    except requests.RequestException as exc:
        return {'success': False, 'error': str(exc), 'message': 'Error de conexión al crear Key'}


def generar_token(key: str) -> dict:
    """
    Paso 2: Genera un JWT de corta duración a partir de la API Key permanente.

    POST /api/Auth/token?key=<key>
    """
    url = BASE_URL_V1 + AUTH_ENDPOINTS['AUTH_TOKEN']
    headers = {
        'Accept': 'application/json, text/plain, */*',
        'User-Agent': 'Python-SAT-Client/1.0',
        'Cache-Control': 'no-cache',
    }

    try:
        response = requests.post(url, params={'key': key}, headers=headers, timeout=TIMEOUT, verify=False)
        raw = response.text.strip()

        if response.ok:
            try:
                body = response.json()
            except ValueError:
                body = raw

            token = _extract_string_value(body)
            return {
                'success': True,
                'access_token': token or raw,
                'message': 'Token generado correctamente',
                'raw_response': raw,
            }

        try:
            err = response.json()
            msg = err.get('message') or err.get('title') or err.get('detail') or f'Error HTTP {response.status_code}'
        except ValueError:
            msg = f'Error HTTP {response.status_code}'

        return {
            'success': False,
            'error': msg,
            'message': 'Error al generar el token',
            'raw_response': raw,
            'http_code': response.status_code,
        }

    except requests.RequestException as exc:
        return {'success': False, 'error': str(exc), 'message': 'Error de conexión al generar token'}
