# Generated by Copilot
import logging
import requests
from config.api import BASE_URL, ENDPOINTS, TIMEOUT

logger = logging.getLogger(__name__)


def descargar_csf(rfc: str, authorization: str, contrasena: str, llave_privada, certificado) -> dict:
    """
    Descarga la Constancia de Situación Fiscal usando FIEL.

    Args:
        rfc: RFC del contribuyente.
        authorization: Token Bearer de la API.
        contrasena: Contraseña de la FIEL.
        llave_privada: FileStorage con el archivo .key.
        certificado: FileStorage con el archivo .cer.

    Returns:
        dict con keys: success, pdf_bytes, file_name, content_type, error.
    """
    url = BASE_URL + ENDPOINTS['CONSULTAR_CSFFIEL']
    logger.info('Iniciando descarga CSF | RFC=%s | URL=%s', rfc, url)

    try:
        files = {
            'llavePrivada': (llave_privada.filename, llave_privada.stream, 'application/octet-stream'),
            'Certificado':  (certificado.filename,   certificado.stream,   'application/octet-stream'),
        }
        data = {'Contrasena': contrasena}
        headers = {
            'RFC':           rfc,
            'Authorization': f'Bearer {authorization}',
            'Accept':        '*/*',
        }

        response = requests.post(url, headers=headers, data=data, files=files, timeout=TIMEOUT, verify=False)
        logger.info('Respuesta CSF | status=%s | content-type=%s', response.status_code, response.headers.get('Content-Type'))

        if response.ok:
            content_type = response.headers.get('Content-Type', 'application/pdf')
            file_name = _extract_filename(response, 'ConstanciaSituacionFiscal.pdf')
            return {'success': True, 'pdf_bytes': response.content, 'file_name': file_name, 'content_type': content_type}

        error_text = response.text
        logger.error('Error CSF | status=%s | body=%s', response.status_code, error_text[:500])
        return {'success': False, 'error': error_text or f'Error {response.status_code}'}

    except Exception as exc:
        logger.exception('Excepción inesperada al descargar CSF')
        return {'success': False, 'error': str(exc)}


def _extract_filename(response: requests.Response, default: str) -> str:
    """Extrae el nombre de archivo del header Content-Disposition."""
    cd = response.headers.get('Content-Disposition', '')
    for part in cd.split(';'):
        part = part.strip()
        if part.startswith('filename='):
            return part[len('filename='):].strip('"')
    return default
