# Generated by Copilot
import logging
from urllib.parse import urlencode
import requests
from config.api import BASE_URL, ENDPOINTS, TIMEOUT

logger = logging.getLogger(__name__)


def consultar_facturas(rfc: str, authorization: str, contrasena: str,
                       llave_privada, certificado,
                       tipo_busqueda: int = 1,
                       estatus_factura: int = -1,
                       fecha_inicial: str = '',
                       fecha_final: str = '',
                       tipo: str = 'recibidos',
                       descarga_comprobantes: bool = False,
                       request_id: str = '') -> dict:
    """
    Consulta facturas del SAT usando FIEL.

    Returns:
        dict con keys: success, data, request_id, message, error.
    """
    params = {
        'tipoBusqueda':       tipo_busqueda,
        'estatusFactura':     estatus_factura,
        'fecha_inicial':      fecha_inicial,
        'fecha_final':        fecha_final,
        'tipo':               tipo,
        'descargaComprobantes': 'TRUE' if descarga_comprobantes else 'FALSE',
    }
    if request_id:
        params['requestId'] = request_id

    url = BASE_URL + ENDPOINTS['CONSULTAR_FACFIEL'] + '?' + urlencode(params)
    logger.info('Consultando facturas | RFC=%s | URL=%s', rfc, url)

    try:
        files = {
            'llavePrivada': (llave_privada.filename, llave_privada.stream, 'application/octet-stream'),
            'Certificado':  (certificado.filename,   certificado.stream,   'application/octet-stream'),
        }
        data = {'Contrasena': contrasena}
        headers = {
            'RFC':           rfc,
            'Authorization': f'Bearer {authorization}',
            'Accept':        'application/json',
        }

        response = requests.post(url, headers=headers, data=data, files=files, timeout=TIMEOUT, verify=False)
        logger.info('Respuesta facturas | status=%s', response.status_code)

        if response.ok:
            try:
                json_data = response.json()
            except Exception:
                json_data = response.text
            req_id = response.headers.get('RequestId') or (json_data.get('requestId') if isinstance(json_data, dict) else None)
            return {'success': True, 'data': json_data, 'request_id': req_id, 'message': 'Consulta exitosa'}

        error_text = response.text
        logger.error('Error facturas | status=%s | body=%s', response.status_code, error_text[:500])
        return {'success': False, 'error': error_text or f'Error {response.status_code}'}

    except Exception as exc:
        logger.exception('Excepción inesperada al consultar facturas')
        return {'success': False, 'error': str(exc)}
