// Generated by Copilot
namespace SatGoCliente.Models
{
    /// <summary>
    /// ViewModel para el formulario de consulta de facturas
    /// </summary>
    public class ConsultaFacturaViewModel
    {
        // Datos FIEL
        public string Rfc { get; set; } = "PESH8805072Q5";
        public string Authorization { get; set; } = string.Empty;
        public string Contrasena { get; set; } = "qwerty12";
        public IFormFile? LlavePrivada { get; set; }
        public IFormFile? Certificado { get; set; }

        // Parámetros de consulta
        public int TipoBusqueda { get; set; } = 1;
        public int EstatusFactura { get; set; } = -1;
        public string FechaInicial { get; set; } = DateTime.Now.AddDays(-30).ToString("yyyy-MM-ddTHH:mm:ss");
        public string FechaFinal { get; set; } = DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss");
        public string Tipo { get; set; } = "recibidos";
        public bool DescargaComprobantes { get; set; } = false;
        public string? RequestId { get; set; }

        // Resultado
        public object? Resultado { get; set; }
        public string? Error { get; set; }
        public bool Success { get; set; }
    }
}
