// Generated by Copilot
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SatGoCliente.Models
{
    /// <summary>
    /// ViewModel unificado para consultas SAT con datos FIEL compartidos
    /// </summary>
    public class ConsultaSatViewModel
    {
        // Datos FIEL compartidos
        [Required(ErrorMessage = "El RFC es requerido")]
        [Display(Name = "RFC")]
        public string Rfc { get; set; } = string.Empty;

        [Required(ErrorMessage = "El token de autorización es requerido")]
        [Display(Name = "Token de Autorización")]
        public string Authorization { get; set; } = string.Empty;

        [Required(ErrorMessage = "La contraseña FIEL es requerida")]
        [Display(Name = "Contraseña FIEL")]
        public string Contrasena { get; set; } = string.Empty;

        [Display(Name = "Llave Privada (.key)")]
        public IFormFile? LlavePrivada { get; set; }

        [Display(Name = "Certificado (.cer)")]
        public IFormFile? Certificado { get; set; }

        // Pestaña activa
        public string ActiveTab { get; set; } = "facturas";

        // Parámetros específicos de Facturas
        [Display(Name = "Request ID")]
        public string? RequestId { get; set; }

        [Display(Name = "Fecha Inicial")]
        public DateTime? FechaInicial { get; set; }

        [Display(Name = "Fecha Final")]
        public DateTime? FechaFinal { get; set; }

        [Display(Name = "RFC del Emisor")]
        public string? RfcEmisor { get; set; }

        [Display(Name = "RFC del Receptor")]
        public string? RfcReceptor { get; set; }

        [Display(Name = "Tipo de Solicitud")]
        public string TipoSolicitud { get; set; } = "CFDI";

        [Display(Name = "Tipo de Comprobante")]
        public string? TipoComprobante { get; set; }

        // Mensajes de respuesta
        public string? Error { get; set; }
        public bool Success { get; set; }
        public string? SuccessMessage { get; set; }

        // Opciones para dropdowns
        public List<SelectListItem> TiposSolicitud => new()
        {
            new SelectListItem("CFDI", "CFDI"),
            new SelectListItem("Metadata", "Metadata")
        };

        public List<SelectListItem> TiposComprobante => new()
        {
            new SelectListItem("Seleccione...", ""),
            new SelectListItem("Ingreso", "I"),
            new SelectListItem("Egreso", "E"),
            new SelectListItem("Traslado", "T"),
            new SelectListItem("Nómina", "N"),
            new SelectListItem("Pago", "P")
        };
    }
}
