// Generated by Copilot
namespace SatGoCliente.Models
{
    /// <summary>
    /// Parámetros de consulta de facturas
    /// </summary>
    public class ConsultaFacturaParams
    {
        public int TipoBusqueda { get; set; } = 1;
        public int EstatusFactura { get; set; } = -1;
        public string FechaInicial { get; set; } = string.Empty;
        public string Tipo { get; set; } = "recibidos";
        public bool DescargaComprobantes { get; set; } = false;
        public string FechaFinal { get; set; } = string.Empty;
        public string? RequestId { get; set; }
    }
}
