// Generated by Copilot
namespace SatGoCliente.Models
{
    /// <summary>
    /// ViewModel para consultas usando CIEC (Clave de Identificación Electrónica Confidencial).
    /// Solo requiere RFC, token y clave CIEC — sin archivos .key/.cer.
    /// </summary>
    public class ConsultaCiecViewModel
    {
        public string Rfc { get; set; } = string.Empty;
        public string Authorization { get; set; } = string.Empty;
        public string Ciec { get; set; } = string.Empty;

        // Parámetros específicos para facturas CIEC
        public string Tipo { get; set; } = "recibidos";
        public int TipoBusqueda { get; set; } = 1;
        public int EstatusFactura { get; set; } = -1;
        public string? Anio { get; set; }
        public string? Mes { get; set; }
        public string? Dia { get; set; }
        public string? Uuid { get; set; }
        public string? RequestId { get; set; }
    }
}
