// Generated by Copilot
using System.ComponentModel.DataAnnotations;

namespace SatGoCliente.Models
{
    /// <summary>Parámetros de consulta compartidos entre FIEL y CIEC.</summary>
    public class DeclaracionParamsBase
    {
        /// <summary>Ejercicio fiscal (año, ej. 2024).</summary>
        [Required]
        public int Ejercicio { get; set; } = DateTime.Today.Year;

        /// <summary>Mes fiscal: 1-12. Usar 0 para todo el año.</summary>
        [Required]
        public int Mes { get; set; } = DateTime.Today.Month;

        /// <summary>RequestId de sesión previo (opcional, acelera la respuesta).</summary>
        public string? RequestId { get; set; }
    }

    /// <summary>ViewModel para descarga de declaraciones via FIEL.</summary>
    public class DeclaracionFielViewModel : DeclaracionParamsBase
    {
        public string Rfc { get; set; } = string.Empty;
        public string Authorization { get; set; } = string.Empty;
        public string Contrasena { get; set; } = string.Empty;
        public IFormFile? LlavePrivada { get; set; }
        public IFormFile? Certificado { get; set; }

        /// <summary>Tipo de documento: "declaracion" o "pago".</summary>
        public string TipoDocumento { get; set; } = "declaracion";
    }

    /// <summary>ViewModel para descarga de declaraciones via CIEC.</summary>
    public class DeclaracionCiecViewModel : DeclaracionParamsBase
    {
        public string Rfc { get; set; } = string.Empty;
        public string Authorization { get; set; } = string.Empty;
        public string Ciec { get; set; } = string.Empty;
    }
}
