// Generated by Copilot
namespace SatGoCliente.Models
{
    /// <summary>
    /// Datos de la FIEL del contribuyente
    /// </summary>
    public class FielData
    {
        public string Rfc { get; set; } = string.Empty;
        public string Authorization { get; set; } = string.Empty;
        public string Contrasena { get; set; } = string.Empty;
        public IFormFile? LlavePrivada { get; set; }
        public IFormFile? Certificado { get; set; }
    }
}
