// Generated by Copilot
namespace SatGoCliente.Models
{
    public class InfoFiscalFielViewModel
    {
        public string Rfc { get; set; } = string.Empty;
        public string Authorization { get; set; } = string.Empty;
        public string Contrasena { get; set; } = string.Empty;
        public IFormFile? LlavePrivada { get; set; }
        public IFormFile? Certificado { get; set; }
        public string? RequestId { get; set; }
    }

    public class InfoFiscalCiecViewModel
    {
        public string Rfc { get; set; } = string.Empty;
        public string Authorization { get; set; } = string.Empty;
        public string Ciec { get; set; } = string.Empty;
        public string? RequestId { get; set; }
    }
}
