// Generated by Copilot
namespace SatGoCliente.Models
{
    /// <summary>
    /// ViewModel para el formulario de descarga de Opinión de Cumplimiento
    /// </summary>
    public class OpinionCumplimientoViewModel
    {
        // Datos FIEL
        public string Rfc { get; set; } = "PESH8805072Q5";
        public string Authorization { get; set; } = string.Empty;
        public string Contrasena { get; set; } = "qwerty12";
        public IFormFile? LlavePrivada { get; set; }
        public IFormFile? Certificado { get; set; }

        // Resultado
        public string? Error { get; set; }
        public bool Success { get; set; }
        public string? SuccessMessage { get; set; }
    }
}
