// Generated by Copilot
export const API_CONFIG = {
  BASE_URL: 'https://api.sat-go.com/api/v2',
  ENDPOINTS: {
    CONSULTAR_FACFIEL: '/Consultar/facfiel',
    CONSULTAR_OCFIEL: '/Consultar/ocfiel',
    CONSULTAR_CSFFIEL: '/Consultar/csffiel'
  },
  TIMEOUT: 30000,
  DEFAULT_HEADERS: {
    'Accept': '*/*',
    'User-Agent': 'React-SAT-Client/1.0',
    'Cache-Control': 'no-cache'
  }
};

export const FORM_DEFAULTS = {
  RFC: 'PESH8805072Q5',
  CONTRASENA: 'qwerty12',
  TIPO_BUSQUEDA: 1,
  ESTATUS_FACTURA: -1,
  TIPO: 'recibidos' as const,
  DESCARGA_COMPROBANTES: false,
  FECHA_INICIAL: '2025-12-01T00:00:00',
  FECHA_FINAL: '2025-12-02T23:59:59'
};