# Generated by Copilot

BASE_URL = 'https://api.sat-go.com/api/v2'

ENDPOINTS = {
    'CONSULTAR_FACFIEL': '/Consultar/facfiel',
    'CONSULTAR_CSFFIEL': '/Consultar/csffiel',
    'CONSULTAR_OCFIEL':  '/Consultar/ocfiel',
}

TIMEOUT = 60  # segundos
