# Generated by Copilot

BASE_URL    = 'https://api.sat-go.com/api/v2'
BASE_URL_V1 = 'https://api.sat-go.com'

ENDPOINTS = {
    'CONSULTAR_FACFIEL': '/Consultar/facfiel',
    'CONSULTAR_FAC':     '/Consultar/fac',
    'CONSULTAR_CSFFIEL': '/Consultar/csffiel',
    'CONSULTAR_CSF':     '/Consultar/csf',
    'CONSULTAR_OCFIEL':  '/Consultar/ocfiel',
    'CONSULTAR_OC':      '/Consultar/oc',
    'CONSULTAR_DECFIEL':      '/Consultar/decfiel',
    'CONSULTAR_DEC':          '/Consultar/dec',
    'CONSULTAR_INFOFISCALFIEL': '/Consultar/informacionfiscalfiel',
    'CONSULTAR_INFOFISCAL':   '/Consultar/informacionfiscal',
}

AUTH_ENDPOINTS = {
    'CREATE_KEY': '/api/v1/Users/CreateKey',
    'AUTH_TOKEN': '/api/Auth/token',
}

TIMEOUT = 60  # segundos
