// Generated by Copilot
import axios from 'axios';
import type { AxiosResponse } from 'axios';
import type { ConsultaFacturaParams, FacturaFielRequest, FacturaResponse } from '../types/FacturaTypes';
import { API_CONFIG } from '../config/api';

// Función para convertir fecha del formato ISO al formato requerido por la API
const formatFechaParaAPI = (fechaISO: string): string => {
  // Convertir de 2025-10-02T01:30:59 a 2025-10-02 01:30:59
  // O de 2025-10-01T12:12 a 2025-10-01 12:12:00
  const fechaConEspacio = fechaISO.replace('T', ' ');
  
  // Si no tiene segundos, agregarlos
  if (fechaConEspacio.length === 16) { // yyyy-mm-dd hh:mm
    return fechaConEspacio + ':00';
  }
  
  return fechaConEspacio;
};

// Configurar axios para el cliente
const api = axios.create({
  baseURL: API_CONFIG.BASE_URL,
  timeout: API_CONFIG.TIMEOUT,
  headers: API_CONFIG.DEFAULT_HEADERS
});

export const consultarFacturaFiel = async (
  params: ConsultaFacturaParams,
  request: FacturaFielRequest
): Promise<FacturaResponse> => {
  try {
    // Crear FormData para enviar archivos
    const formData = new FormData();
    
    // Agregar archivos si existen
    if (request.llave_privada) {
      formData.append('llavePrivada', request.llave_privada, request.llave_privada.name);
    }
    
    if (request.certificado) {
      formData.append('Certificado', request.certificado, request.certificado.name);
    }
    
    // Agregar contraseña
    formData.append('Contrasena', request.contrasena);

    // Construir query parameters
    const queryParams = new URLSearchParams({
      tipoBusqueda: params.tipo_busqueda.toString(),
      estatusFactura: params.estatus_factura.toString(),
      fecha_inicial: formatFechaParaAPI(params.fecha_inicial),
      tipo: params.tipo,
      descargaComprobantes: params.descarga_comprobantes.toString().toUpperCase(),
      fecha_final: formatFechaParaAPI(params.fecha_final)
    });

    // Agregar requestId si existe para reusar sesión
    if (request.request_id && request.request_id.trim() !== '') {
      queryParams.append('requestId', request.request_id);
    }

    // Hacer la petición POST con FormData y query parameters
    const response: AxiosResponse = await api.post(
      `${API_CONFIG.ENDPOINTS.CONSULTAR_FACFIEL}?${queryParams.toString()}`,
      formData,
      {
        headers: {
          'RFC': request.rfc,
          'Authorization': `Bearer ${request.authorization}`,
          'Content-Type': 'multipart/form-data',
        },
      }
    );

    return {
      success: true,
      data: response.data,
      message: 'Consulta realizada exitosamente'
    };

  } catch (error: any) {
    console.error('Error en consultarFacturaFiel:', error);
    
    return {
      success: false,
      error: error.response?.data?.message || error.message || 'Error desconocido',
      message: 'Error al consultar facturas'
    };
  }
};