// Generated by Copilot
import axios from 'axios';
import type { OcFielRequest, OcResponse } from '../types/OcTypes';
import { API_CONFIG } from '../config/api';

// Configurar axios para el cliente
const api = axios.create({
  baseURL: API_CONFIG.BASE_URL,
  timeout: API_CONFIG.TIMEOUT,
  headers: API_CONFIG.DEFAULT_HEADERS
});

export const consultarOpinionCumplimiento = async (
  request: OcFielRequest
): Promise<OcResponse> => {
  try {
    // Crear FormData para enviar archivos
    const formData = new FormData();
    
    // Agregar archivos si existen
    if (request.llave_privada) {
      formData.append('llavePrivada', request.llave_privada, request.llave_privada.name);
    }
    
    if (request.certificado) {
      formData.append('Certificado', request.certificado, request.certificado.name);
    }
    
    // Agregar contraseña
    formData.append('Contrasena', request.contrasena);

    // Hacer la petición POST con FormData
    const response = await api.post(
      API_CONFIG.ENDPOINTS.CONSULTAR_OCFIEL,
      formData,
      {
        headers: {
          'RFC': request.rfc,
          'Authorization': `Bearer ${request.authorization}`,
          'Content-Type': 'multipart/form-data',
        },
        responseType: 'blob' // Esperamos un PDF como respuesta
      }
    );

    return {
      success: true,
      data: response.data,
      message: 'Opinión de cumplimiento descargada exitosamente'
    };

  } catch (error: any) {
    console.error('Error en consultarOpinionCumplimiento:', error);
    
    // Manejar errores 400 que pueden ser texto o JSON
    if (error.response) {
      const contentType = error.response.headers['content-type'] || '';
      
      if (contentType.includes('application/json')) {
        // Intenta parsear como JSON
        try {
          const text = await error.response.data.text();
          const jsonError = JSON.parse(text);
          return {
            success: false,
            error: jsonError.message || jsonError.error || 'Error en la solicitud',
            error_type: 'json',
            error_data: jsonError,
            message: 'Error al consultar opinión de cumplimiento'
          };
        } catch {
          // Si falla el parseo, tratar como texto
          const text = await error.response.data.text();
          return {
            success: false,
            error: text || 'Error desconocido',
            error_type: 'text',
            message: 'Error al consultar opinión de cumplimiento'
          };
        }
      } else {
        // Tratar como texto plano
        try {
          const text = await error.response.data.text();
          return {
            success: false,
            error: text || 'Error desconocido',
            error_type: 'text',
            message: 'Error al consultar opinión de cumplimiento'
          };
        } catch {
          return {
            success: false,
            error: error.message || 'Error desconocido',
            message: 'Error al consultar opinión de cumplimiento'
          };
        }
      }
    }
    
    return {
      success: false,
      error: error.message || 'Error desconocido',
      message: 'Error al consultar opinión de cumplimiento'
    };
  }
};

// Función auxiliar para descargar el PDF
export const downloadPdf = (blob: Blob, filename: string = 'OpinionDeCumplimiento.pdf') => {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
};
